/* ─────────────────────────────────────────────────────────────
   TEXTOS DE LA APLICACIÓN

   Formato «clave mayor»: cada clave lleva sus seis traducciones
   juntas en la misma línea. Es más incómodo de escribir que un
   fichero por idioma, pero hace imposible el fallo típico —añadir
   un texto en español y olvidarlo en los otros cinco— porque el
   hueco se ve a simple vista.

   Orden fijo: en · es · zh · de · fr · ru
   El inglés es el idioma por defecto y el respaldo.

   Sustituciones: {n}, {name}, {time}... ver t() en i18n.js
   ───────────────────────────────────────────────────────────── */

export const STRINGS = {

  // ══════════════════════════ COMÚN ══════════════════════════
  'common.save':        { en: 'Save', es: 'Guardar', zh: '保存', de: 'Speichern', fr: 'Enregistrer', ru: 'Сохранить' },
  'common.saving':      { en: 'Saving', es: 'Guardando', zh: '保存中', de: 'Wird gespeichert', fr: 'Enregistrement', ru: 'Сохранение' },
  'common.cancel':      { en: 'Cancel', es: 'Cancelar', zh: '取消', de: 'Abbrechen', fr: 'Annuler', ru: 'Отмена' },
  'common.delete':      { en: 'Delete', es: 'Eliminar', zh: '删除', de: 'Löschen', fr: 'Supprimer', ru: 'Удалить' },
  'common.edit':        { en: 'Edit', es: 'Editar', zh: '编辑', de: 'Bearbeiten', fr: 'Modifier', ru: 'Изменить' },
  'common.add':         { en: 'Add', es: 'Añadir', zh: '添加', de: 'Hinzufügen', fr: 'Ajouter', ru: 'Добавить' },
  'common.create':      { en: 'Create', es: 'Crear', zh: '创建', de: 'Erstellen', fr: 'Créer', ru: 'Создать' },
  'common.close':       { en: 'Close', es: 'Cerrar', zh: '关闭', de: 'Schließen', fr: 'Fermer', ru: 'Закрыть' },
  'common.back':        { en: 'Back', es: 'Volver', zh: '返回', de: 'Zurück', fr: 'Retour', ru: 'Назад' },
  'common.next':        { en: 'Next', es: 'Siguiente', zh: '下一步', de: 'Weiter', fr: 'Suivant', ru: 'Далее' },
  'common.done':        { en: 'Done', es: 'Listo', zh: '完成', de: 'Fertig', fr: 'Terminé', ru: 'Готово' },
  'common.loading':     { en: 'Loading', es: 'Cargando', zh: '加载中', de: 'Wird geladen', fr: 'Chargement', ru: 'Загрузка' },
  'common.optional':    { en: 'Optional', es: 'Opcional', zh: '可选', de: 'Optional', fr: 'Facultatif', ru: 'Необязательно' },
  'common.none':        { en: 'None', es: 'Ninguno', zh: '无', de: 'Keine', fr: 'Aucun', ru: 'Нет' },
  'common.error':       { en: 'Error', es: 'Error', zh: '错误', de: 'Fehler', fr: 'Erreur', ru: 'Ошибка' },
  'common.name':        { en: 'Name', es: 'Nombre', zh: '名称', de: 'Name', fr: 'Nom', ru: 'Название' },
  'common.date':        { en: 'Date', es: 'Fecha', zh: '日期', de: 'Datum', fr: 'Date', ru: 'Дата' },
  'common.total':       { en: 'Total', es: 'Total', zh: '合计', de: 'Gesamt', fr: 'Total', ru: 'Итого' },
  'common.months12':    { en: '12 months', es: '12 meses', zh: '12 个月', de: '12 Monate', fr: '12 mois', ru: '12 мес.' },
  'common.notes':       { en: 'Notes', es: 'Notas', zh: '备注', de: 'Notizen', fr: 'Notes', ru: 'Заметки' },
  'common.cost':        { en: 'Cost', es: 'Coste', zh: '费用', de: 'Kosten', fr: 'Coût', ru: 'Стоимость' },
  'common.link':        { en: 'Link', es: 'Enlace', zh: '链接', de: 'Link', fr: 'Lien', ru: 'Ссылка' },
  'common.openLink':    { en: 'Open link', es: 'Ver enlace', zh: '打开链接', de: 'Link öffnen', fr: 'Voir le lien', ru: 'Открыть ссылку' },
  'common.reference':   { en: 'Reference', es: 'Referencia', zh: '零件号', de: 'Teilenummer', fr: 'Référence', ru: 'Артикул' },
  'common.state':       { en: 'State', es: 'Estado', zh: '状态', de: 'Zustand', fr: 'État', ru: 'Состояние' },
  'common.register':    { en: 'Log', es: 'Registrar', zh: '记录', de: 'Eintragen', fr: 'Enregistrer', ru: 'Записать' },
  'common.noData':      { en: 'No data', es: 'Sin datos', zh: '暂无数据', de: 'Keine Daten', fr: 'Aucune donnée', ru: 'Нет данных' },
  'common.user':        { en: 'Username', es: 'Usuario', zh: '用户名', de: 'Benutzername', fr: 'Identifiant', ru: 'Пользователь' },
  'common.vehicle':     { en: 'Vehicle', es: 'Vehículo', zh: '车辆', de: 'Fahrzeug', fr: 'Véhicule', ru: 'Машина' },
  'common.vehicles':    { en: 'Vehicles', es: 'Vehículos', zh: '车辆', de: 'Fahrzeuge', fr: 'Véhicules', ru: 'Машины' },
  'common.plate':       { en: 'Plate', es: 'Matrícula', zh: '车牌', de: 'Kennzeichen', fr: 'Immatriculation', ru: 'Госномер' },
  'common.km':          { en: 'km', es: 'km', zh: '公里', de: 'km', fr: 'km', ru: 'км' },
  'common.maintenance': { en: 'Maintenance', es: 'Mantenimiento', zh: '保养', de: 'Wartung', fr: 'Entretien', ru: 'Обслуживание' },
  'common.fuel':        { en: 'Fuel', es: 'Combustible', zh: '燃料', de: 'Kraftstoff', fr: 'Carburant', ru: 'Топливо' },
  'common.phone':       { en: 'Phone', es: 'Teléfono', zh: '电话', de: 'Telefon', fr: 'Téléphone', ru: 'Телефон' },
  'common.address':     { en: 'Address', es: 'Dirección', zh: '地址', de: 'Adresse', fr: 'Adresse', ru: 'Адрес' },

  // ══════════════════════════ NAVEGACIÓN ══════════════════════════
  'nav.vehicles':   { en: 'Vehicles', es: 'Vehículos', zh: '车辆', de: 'Fahrzeuge', fr: 'Véhicules', ru: 'Транспорт' },
  'nav.summary':    { en: 'Summary', es: 'Resumen', zh: '总览', de: 'Übersicht', fr: 'Résumé', ru: 'Сводка' },
  'nav.alerts':     { en: 'Alerts', es: 'Avisos', zh: '提醒', de: 'Hinweise', fr: 'Alertes', ru: 'Напоминания' },
  'nav.groups':     { en: 'Groups', es: 'Grupos', zh: '车友群', de: 'Gruppen', fr: 'Groupes', ru: 'Группы' },
  'nav.workshops':  { en: 'Workshops', es: 'Talleres', zh: '修理厂', de: 'Werkstätten', fr: 'Garages', ru: 'Мастерские' },
  'nav.admin':      { en: 'Admin', es: 'Admin', zh: '管理', de: 'Verwaltung', fr: 'Admin', ru: 'Админ' },
  'nav.logout':     { en: 'Log out', es: 'Salir', zh: '退出', de: 'Abmelden', fr: 'Déconnexion', ru: 'Выйти' },
  'nav.settings':   { en: 'Settings', es: 'Ajustes', zh: '设置', de: 'Einstellungen', fr: 'Réglages', ru: 'Настройки' },
  'nav.lightMode':  { en: 'Light mode', es: 'Modo claro', zh: '浅色模式', de: 'Heller Modus', fr: 'Mode clair', ru: 'Светлая тема' },
  'nav.darkMode':   { en: 'Dark mode', es: 'Modo oscuro', zh: '深色模式', de: 'Dunkler Modus', fr: 'Mode sombre', ru: 'Тёмная тема' },

  // ══════════════════════════ ACCESO ══════════════════════════
  'login.tagline':    { en: 'The lads’ garage', es: 'El taller de los pibes', zh: '哥们儿的车库', de: 'Die Garage der Jungs', fr: 'Le garage des copains', ru: 'Гараж своих' },
  'login.user':       { en: 'Username', es: 'Usuario', zh: '用户名', de: 'Benutzername', fr: 'Identifiant', ru: 'Имя пользователя' },
  'login.userPh':     { en: 'username', es: 'usuario', zh: '用户名', de: 'benutzername', fr: 'identifiant', ru: 'пользователь' },
  'login.pin':        { en: 'PIN', es: 'PIN', zh: 'PIN 码', de: 'PIN', fr: 'Code PIN', ru: 'PIN-код' },
  'login.enter':      { en: 'Sign in', es: 'Entrar', zh: '登录', de: 'Anmelden', fr: 'Se connecter', ru: 'Войти' },
  'login.entering':   { en: 'Signing in', es: 'Entrando', zh: '登录中', de: 'Anmeldung läuft', fr: 'Connexion', ru: 'Вход' },
  'login.errEmpty':   { en: 'Enter your username and PIN', es: 'Introduce usuario y PIN', zh: '请输入用户名和 PIN 码', de: 'Benutzername und PIN eingeben', fr: 'Saisis ton identifiant et ton PIN', ru: 'Введите имя пользователя и PIN' },
  'login.errCreds':   { en: 'Wrong username or PIN', es: 'Usuario o PIN incorrecto', zh: '用户名或 PIN 码错误', de: 'Benutzername oder PIN falsch', fr: 'Identifiant ou PIN incorrect', ru: 'Неверное имя пользователя или PIN' },
  'login.errTooMany': { en: 'Too many attempts. Wait {time}', es: 'Demasiados intentos. Espera {time}', zh: '尝试次数过多，请等待 {time}', de: 'Zu viele Versuche. Warte {time}', fr: 'Trop de tentatives. Attends {time}', ru: 'Слишком много попыток. Подождите {time}' },
  'login.locked':     { en: 'Locked', es: 'Bloqueado', zh: '已锁定', de: 'Gesperrt', fr: 'Bloqué', ru: 'Заблокировано' },
  'login.noDb':       { en: 'No database is configured in this environment. Open the demo to see it working.', es: 'No hay base de datos configurada en este entorno. Entra en la demo para verla funcionando.', zh: '当前环境未配置数据库。可以打开演示版查看效果。', de: 'In dieser Umgebung ist keine Datenbank eingerichtet. Öffne die Demo, um sie in Aktion zu sehen.', fr: 'Aucune base de données n’est configurée dans cet environnement. Ouvre la démo pour la voir fonctionner.', ru: 'В этой среде база данных не настроена. Откройте демоверсию, чтобы посмотреть, как всё работает.' },
  'login.demoBody':   { en: 'Just want a look around?', es: '¿Solo quieres echar un vistazo?', zh: '只想随便看看？', de: 'Nur mal reinschauen?', fr: 'Juste envie de jeter un œil ?', ru: 'Просто хотите посмотреть?' },
  'login.demoBtn':    { en: 'Open the demo', es: 'Entrar en la demo', zh: '打开演示版', de: 'Demo öffnen', fr: 'Ouvrir la démo', ru: 'Открыть демоверсию' },

  // ══════════════════════════ BIENVENIDA ══════════════════════════
  'onb.welcome':    { en: 'Welcome', es: 'Bienvenido', zh: '欢迎', de: 'Willkommen', fr: 'Bienvenue', ru: 'Добро пожаловать' },
  'onb.intro':      { en: 'Three quick questions before you start. You can change all of it later in Settings.', es: 'Tres preguntas rápidas antes de empezar. Todo esto se puede cambiar luego en Ajustes.', zh: '开始前有三个简单的问题。之后都可以在设置里修改。', de: 'Drei kurze Fragen, bevor es losgeht. Alles lässt sich später in den Einstellungen ändern.', fr: 'Trois questions rapides avant de commencer. Tout est modifiable ensuite dans les Réglages.', ru: 'Три быстрых вопроса перед началом. Всё это потом можно изменить в настройках.' },
  'onb.langQ':      { en: 'What language do you prefer?', es: '¿En qué idioma lo prefieres?', zh: '你想使用哪种语言？', de: 'Welche Sprache möchtest du?', fr: 'Quelle langue préfères-tu ?', ru: 'Какой язык предпочитаете?' },
  'onb.themeQ':     { en: 'Light or dark?', es: '¿Claro u oscuro?', zh: '浅色还是深色？', de: 'Hell oder dunkel?', fr: 'Clair ou sombre ?', ru: 'Светлая или тёмная?' },
  'onb.accentQ':    { en: 'Pick your accent colour', es: 'Elige tu color de acento', zh: '选择你的强调色', de: 'Wähle deine Akzentfarbe', fr: 'Choisis ta couleur d’accent', ru: 'Выберите акцентный цвет' },
  'onb.accentNote': { en: 'The background stays graphite. Only the accent changes.', es: 'El fondo sigue siendo grafito. Lo único que cambia es el acento.', zh: '背景始终是石墨灰，只有强调色会变。', de: 'Der Hintergrund bleibt Graphit. Nur der Akzent ändert sich.', fr: 'Le fond reste graphite. Seul l’accent change.', ru: 'Фон остаётся графитовым. Меняется только акцент.' },
  'onb.dark':       { en: 'Dark', es: 'Oscuro', zh: '深色', de: 'Dunkel', fr: 'Sombre', ru: 'Тёмная' },
  'onb.light':      { en: 'Light', es: 'Claro', zh: '浅色', de: 'Hell', fr: 'Clair', ru: 'Светлая' },
  'onb.darkNote':   { en: 'Graphite background. Easier at night.', es: 'Fondo grafito. Más cómodo de noche.', zh: '石墨灰背景，夜间更舒适。', de: 'Graphit-Hintergrund. Angenehmer bei Nacht.', fr: 'Fond graphite. Plus confortable la nuit.', ru: 'Графитовый фон. Удобнее ночью.' },
  'onb.lightNote':  { en: 'Paper background. Easier in daylight.', es: 'Fondo papel. Más cómodo con luz.', zh: '纸白背景，白天更舒适。', de: 'Papier-Hintergrund. Angenehmer bei Tageslicht.', fr: 'Fond papier. Plus confortable en plein jour.', ru: 'Бумажный фон. Удобнее при дневном свете.' },
  'onb.finish':     { en: 'Start', es: 'Empezar', zh: '开始使用', de: 'Los geht’s', fr: 'Commencer', ru: 'Начать' },
  'onb.saved':      { en: 'Preferences saved', es: 'Preferencias guardadas', zh: '偏好已保存', de: 'Einstellungen gespeichert', fr: 'Préférences enregistrées', ru: 'Настройки сохранены' },
  'onb.step':       { en: 'Step {n} of 3', es: 'Paso {n} de 3', zh: '第 {n} 步，共 3 步', de: 'Schritt {n} von 3', fr: 'Étape {n} sur 3', ru: 'Шаг {n} из 3' },
  'onb.preview':    { en: 'Preview', es: 'Vista previa', zh: '预览', de: 'Vorschau', fr: 'Aperçu', ru: 'Предпросмотр' },

  // ══════════════════════════ AJUSTES ══════════════════════════
  'set.title':      { en: 'Settings', es: 'Ajustes', zh: '设置', de: 'Einstellungen', fr: 'Réglages', ru: 'Настройки' },
  'set.language':   { en: 'Language', es: 'Idioma', zh: '语言', de: 'Sprache', fr: 'Langue', ru: 'Язык' },
  'set.theme':      { en: 'Theme', es: 'Tema', zh: '主题', de: 'Erscheinungsbild', fr: 'Thème', ru: 'Тема' },
  'set.accent':     { en: 'Accent colour', es: 'Color de acento', zh: '强调色', de: 'Akzentfarbe', fr: 'Couleur d’accent', ru: 'Акцентный цвет' },
  'set.saved':      { en: 'Preferences saved', es: 'Preferencias guardadas', zh: '偏好已保存', de: 'Einstellungen gespeichert', fr: 'Préférences enregistrées', ru: 'Настройки сохранены' },
  'set.savedLocal': { en: 'Saved on this device only — the database could not be reached', es: 'Guardado solo en este dispositivo — no se pudo llegar a la base de datos', zh: '仅保存在本设备 — 无法连接到数据库', de: 'Nur auf diesem Gerät gespeichert — die Datenbank war nicht erreichbar', fr: 'Enregistré sur cet appareil uniquement — base de données injoignable', ru: 'Сохранено только на этом устройстве — база данных недоступна' },

  // ══════════════════════════ PIN ══════════════════════════
  'pin.title':   { en: 'Change your PIN', es: 'Cambiar PIN', zh: '修改 PIN 码', de: 'PIN ändern', fr: 'Changer de PIN', ru: 'Смена PIN-кода' },
  'pin.intro':   { en: 'This is your first sign-in. Choose a new PIN for safety.', es: 'Es tu primer inicio de sesión. Por seguridad, elige un PIN nuevo.', zh: '这是你第一次登录。为了安全，请设置新的 PIN 码。', de: 'Das ist deine erste Anmeldung. Wähle aus Sicherheitsgründen eine neue PIN.', fr: 'C’est ta première connexion. Par sécurité, choisis un nouveau PIN.', ru: 'Это ваш первый вход. Для безопасности выберите новый PIN-код.' },
  'pin.new':     { en: 'New PIN', es: 'Nuevo PIN', zh: '新 PIN 码', de: 'Neue PIN', fr: 'Nouveau PIN', ru: 'Новый PIN-код' },
  'pin.confirm': { en: 'Confirm PIN', es: 'Confirmar PIN', zh: '确认 PIN 码', de: 'PIN bestätigen', fr: 'Confirmer le PIN', ru: 'Подтвердите PIN-код' },
  'pin.min':     { en: 'At least 4 digits', es: 'Mínimo 4 dígitos', zh: '至少 4 位数字', de: 'Mindestens 4 Ziffern', fr: 'Au moins 4 chiffres', ru: 'Минимум 4 цифры' },
  'pin.repeat':  { en: 'Repeat the PIN', es: 'Repite el PIN', zh: '再次输入 PIN 码', de: 'PIN wiederholen', fr: 'Répète le PIN', ru: 'Повторите PIN-код' },
  'pin.errShort':{ en: 'The PIN must be at least 4 digits', es: 'El PIN debe tener al menos 4 dígitos', zh: 'PIN 码至少需要 4 位数字', de: 'Die PIN muss mindestens 4 Ziffern haben', fr: 'Le PIN doit compter au moins 4 chiffres', ru: 'PIN-код должен состоять минимум из 4 цифр' },
  'pin.errMatch':{ en: 'The PINs do not match', es: 'Los PIN no coinciden', zh: '两次输入的 PIN 码不一致', de: 'Die PINs stimmen nicht überein', fr: 'Les PIN ne correspondent pas', ru: 'PIN-коды не совпадают' },
  'pin.saveBtn': { en: 'Save new PIN', es: 'Guardar PIN', zh: '保存 PIN 码', de: 'PIN speichern', fr: 'Enregistrer le PIN', ru: 'Сохранить PIN-код' },

  // ══════════════════════════ VEHÍCULOS ══════════════════════════
  'dash.title':          { en: 'My vehicles', es: 'Mis vehículos', zh: '我的车辆', de: 'Meine Fahrzeuge', fr: 'Mes véhicules', ru: 'Мой транспорт' },
  'dash.noneYet':        { en: 'None registered', es: 'Ninguno registrado', zh: '尚未登记', de: 'Noch keine erfasst', fr: 'Aucun enregistré', ru: 'Ничего не добавлено' },
  'dash.units':          { en: '{n} vehicles', es: '{n} unidades', zh: '{n} 辆车', de: '{n} Fahrzeuge', fr: '{n} véhicules', ru: '{n} машин' },
  'dash.unit':           { en: '1 vehicle', es: '1 unidad', zh: '1 辆车', de: '1 Fahrzeug', fr: '1 véhicule', ru: '1 машина' },
  'dash.needAttention':  { en: '{n} need attention', es: '{n} requieren atención', zh: '{n} 辆需要处理', de: '{n} brauchen Aufmerksamkeit', fr: '{n} demandent attention', ru: '{n} требуют внимания' },
  'dash.needAttention1': { en: '1 needs attention', es: '1 requiere atención', zh: '1 辆需要处理', de: '1 braucht Aufmerksamkeit', fr: '1 demande attention', ru: '1 требует внимания' },
  'dash.allGood':        { en: 'all up to date', es: 'todo al día', zh: '一切正常', de: 'alles aktuell', fr: 'tout est à jour', ru: 'всё в порядке' },
  'dash.empty':          { en: 'You have no vehicles yet', es: 'Aún no tienes vehículos registrados', zh: '你还没有登记任何车辆', de: 'Du hast noch keine Fahrzeuge erfasst', fr: 'Tu n’as encore aucun véhicule', ru: 'Вы ещё не добавили ни одной машины' },
  'dash.addFirst':       { en: 'Add your first', es: 'Añadir el primero', zh: '添加第一辆', de: 'Erstes hinzufügen', fr: 'Ajouter le premier', ru: 'Добавить первую' },
  'dash.deleteConfirm':  { en: 'Delete this vehicle and all of its data?', es: '¿Eliminar este vehículo y todos sus datos?', zh: '删除这辆车及其全部数据？', de: 'Dieses Fahrzeug und alle seine Daten löschen?', fr: 'Supprimer ce véhicule et toutes ses données ?', ru: 'Удалить эту машину и все её данные?' },
  'dash.added':          { en: 'Vehicle added', es: 'Vehículo añadido', zh: '车辆已添加', de: 'Fahrzeug hinzugefügt', fr: 'Véhicule ajouté', ru: 'Машина добавлена' },
  'dash.deleted':        { en: 'Vehicle deleted', es: 'Vehículo eliminado', zh: '车辆已删除', de: 'Fahrzeug gelöscht', fr: 'Véhicule supprimé', ru: 'Машина удалена' },
  'dash.new':            { en: 'New vehicle', es: 'Nuevo vehículo', zh: '新增车辆', de: 'Neues Fahrzeug', fr: 'Nouveau véhicule', ru: 'Новая машина' },
  'dash.type':           { en: 'Vehicle type', es: 'Tipo de vehículo', zh: '车辆类型', de: 'Fahrzeugtyp', fr: 'Type de véhicule', ru: 'Тип транспорта' },
  'dash.plate':          { en: 'Plate', es: 'Matrícula', zh: '车牌', de: 'Kennzeichen', fr: 'Immatriculation', ru: 'Госномер' },
  'dash.brand':          { en: 'Make', es: 'Marca', zh: '品牌', de: 'Marke', fr: 'Marque', ru: 'Марка' },
  'dash.model':          { en: 'Model', es: 'Modelo', zh: '型号', de: 'Modell', fr: 'Modèle', ru: 'Модель' },
  'dash.year':           { en: 'Year', es: 'Año', zh: '年份', de: 'Baujahr', fr: 'Année', ru: 'Год' },
  'dash.transmission':   { en: 'Transmission', es: 'Transmisión', zh: '变速箱', de: 'Getriebe', fr: 'Boîte de vitesses', ru: 'Коробка передач' },
  'dash.fuel':           { en: 'Fuel', es: 'Combustible', zh: '燃料', de: 'Kraftstoff', fr: 'Carburant', ru: 'Топливо' },
  'dash.currentKm':      { en: 'Current km', es: 'Km actuales', zh: '当前里程', de: 'Aktueller km-Stand', fr: 'Km actuels', ru: 'Текущий пробег' },
  'dash.notes':          { en: 'Notes', es: 'Notas', zh: '备注', de: 'Notizen', fr: 'Notes', ru: 'Заметки' },
  'dash.parts':          { en: '{n} parts', es: '{n} recambios', zh: '{n} 个配件', de: '{n} Ersatzteile', fr: '{n} pièces', ru: 'Запчастей: {n}' },
  'dash.overdue':        { en: '{n} overdue', es: '{n} vencidos', zh: '{n} 项已逾期', de: '{n} überfällig', fr: '{n} en retard', ru: 'Просрочено: {n}' },
  'dash.upcoming':       { en: '{n} due soon', es: '{n} próximos', zh: '{n} 项即将到期', de: '{n} stehen an', fr: '{n} à prévoir', ru: 'Скоро: {n}' },
  'dash.upToDate':       { en: 'All up to date', es: 'Todo al día', zh: '全部正常', de: 'Alles aktuell', fr: 'Tout est à jour', ru: 'Всё в порядке' },
  'dash.noMaint':        { en: 'No maintenance yet', es: 'Sin mantenimientos', zh: '暂无保养记录', de: 'Noch keine Wartung', fr: 'Aucun entretien', ru: 'Обслуживания нет' },
  'dash.itvExpired':     { en: 'Inspection expired', es: 'ITV caducada', zh: '年检已过期', de: 'HU abgelaufen', fr: 'Contrôle expiré', ru: 'Техосмотр просрочен' },
  'dash.itvNegative':    { en: 'Inspection failed', es: 'ITV negativa', zh: '年检未通过', de: 'HU nicht bestanden', fr: 'Contrôle non validé', ru: 'Техосмотр не пройден' },
  'dash.itvDays':        { en: 'Inspection {n} d', es: 'ITV {n} d', zh: '年检剩 {n} 天', de: 'HU {n} T', fr: 'Contrôle {n} j', ru: 'Техосмотр {n} дн.' },
  'dash.gaugeLabel':     { en: 'State', es: 'Estado', zh: '状态', de: 'Zustand', fr: 'État', ru: 'Состояние' },

  // ══════════════════════════ DETALLE DEL VEHÍCULO ══════════════════════════
  'car.loadError':    { en: 'Error loading data: ', es: 'Error cargando datos: ', zh: '加载数据出错：', de: 'Fehler beim Laden der Daten: ', fr: 'Erreur de chargement : ', ru: 'Ошибка загрузки данных: ' },
  'car.updated':      { en: 'Vehicle updated', es: 'Vehículo actualizado', zh: '车辆已更新', de: 'Fahrzeug aktualisiert', fr: 'Véhicule mis à jour', ru: 'Машина обновлена' },
  'car.editTitle':    { en: 'Edit vehicle', es: 'Editar vehículo', zh: '编辑车辆', de: 'Fahrzeug bearbeiten', fr: 'Modifier le véhicule', ru: 'Изменить машину' },
  'car.exportPdf':    { en: 'Export PDF', es: 'Exportar PDF', zh: '导出 PDF', de: 'PDF exportieren', fr: 'Exporter en PDF', ru: 'Экспорт в PDF' },
  'car.exportExcel':  { en: 'Export Excel', es: 'Exportar Excel', zh: '导出 Excel', de: 'Excel exportieren', fr: 'Exporter en Excel', ru: 'Экспорт в Excel' },
  'car.fullReport':   { en: 'Full report', es: 'Informe completo', zh: '完整报告', de: 'Vollständiger Bericht', fr: 'Rapport complet', ru: 'Полный отчёт' },
  'car.sheetData':    { en: 'Data in sheets', es: 'Datos en hojas', zh: '表格数据', de: 'Daten in Tabellen', fr: 'Données en feuilles', ru: 'Данные по листам' },
  'car.exportPdfErr': { en: 'PDF export failed: ', es: 'Error al exportar PDF: ', zh: 'PDF 导出失败：', de: 'PDF-Export fehlgeschlagen: ', fr: 'Échec de l’export PDF : ', ru: 'Не удалось экспортировать PDF: ' },
  'car.exportXlsErr': { en: 'Excel export failed: ', es: 'Error al exportar Excel: ', zh: 'Excel 导出失败：', de: 'Excel-Export fehlgeschlagen: ', fr: 'Échec de l’export Excel : ', ru: 'Не удалось экспортировать Excel: ' },
  'car.tabMaint':     { en: 'Maintenance', es: 'Mantenimientos', zh: '保养', de: 'Wartung', fr: 'Entretien', ru: 'Обслуживание' },
  'car.tabMaintShort':{ en: 'Maint.', es: 'Mant.', zh: '保养', de: 'Wartung', fr: 'Entret.', ru: 'ТО' },
  'car.tabTodos':     { en: 'Tasks', es: 'Tareas', zh: '待办', de: 'Aufgaben', fr: 'Tâches', ru: 'Задачи' },
  'car.tabParts':     { en: 'Parts', es: 'Recambios', zh: '配件', de: 'Ersatzteile', fr: 'Pièces', ru: 'Запчасти' },
  'car.tabFuel':      { en: 'Refuelling', es: 'Repostajes', zh: '加油', de: 'Tankvorgänge', fr: 'Pleins', ru: 'Заправки' },
  'car.tabFuelShort': { en: 'Fuel', es: 'Fuel', zh: '加油', de: 'Tanken', fr: 'Plein', ru: 'Топливо' },
  'car.tabExpenses':  { en: 'Expenses', es: 'Gastos', zh: '花费', de: 'Ausgaben', fr: 'Dépenses', ru: 'Расходы' },
  'car.interval':     { en: 'Interval', es: 'Intervalo', zh: '周期', de: 'Intervall', fr: 'Intervalle', ru: 'Интервал' },
  'car.workshop':     { en: 'Workshop', es: 'Taller', zh: '维修店', de: 'Werkstatt', fr: 'Garage', ru: 'Мастерская' },
  'car.noWorkshop':   { en: 'Not specified', es: 'Sin especificar', zh: '未指定', de: 'Nicht angegeben', fr: 'Non précisé', ru: 'Не указано' },
  'car.tabKm':        { en: 'Kilometres', es: 'Kilómetros', zh: '里程', de: 'Kilometer', fr: 'Kilomètres', ru: 'Пробег' },
  'car.tabKmShort':   { en: 'Km', es: 'Km', zh: '里程', de: 'Km', fr: 'Km', ru: 'Км' },
  'car.logKm':        { en: 'Log km', es: 'Registrar km', zh: '记录里程', de: 'km eintragen', fr: 'Saisir les km', ru: 'Записать пробег' },
  'car.kmLogged':     { en: 'Kilometres logged', es: 'Kilómetros registrados', zh: '里程已记录', de: 'Kilometerstand eingetragen', fr: 'Kilométrage enregistré', ru: 'Пробег записан' },
  'car.noRecords':    { en: 'Nothing logged yet', es: 'Sin registros aún', zh: '暂无记录', de: 'Noch keine Einträge', fr: 'Aucun enregistrement', ru: 'Записей пока нет' },
  'car.lastKm':       { en: 'Last (km)', es: 'Último (km)', zh: '上次（公里）', de: 'Letzter (km)', fr: 'Dernier (km)', ru: 'Прошлое (км)' },
  'car.nextKm':       { en: 'Next (km)', es: 'Próximo (km)', zh: '下次（公里）', de: 'Nächster (km)', fr: 'Prochain (km)', ru: 'Следующее (км)' },
  'car.lastDate':     { en: 'Last date', es: 'Fecha últ.', zh: '上次日期', de: 'Letztes Datum', fr: 'Date préc.', ru: 'Прошлая дата' },
  'car.nextDate':     { en: 'Next date', es: 'Fecha próx.', zh: '下次日期', de: 'Nächstes Datum', fr: 'Date proch.', ru: 'Следующая дата' },
  'car.every':        { en: 'Every {km} km', es: 'Cada {km} km', zh: '每 {km} 公里', de: 'Alle {km} km', fr: 'Tous les {km} km', ru: 'Каждые {km} км' },
  'car.addPart':      { en: 'Add part', es: 'Añadir recambio', zh: '添加配件', de: 'Ersatzteil hinzufügen', fr: 'Ajouter une pièce', ru: 'Добавить запчасть' },
  'car.partAdded':    { en: 'Part added', es: 'Recambio añadido', zh: '配件已添加', de: 'Ersatzteil hinzugefügt', fr: 'Pièce ajoutée', ru: 'Запчасть добавлена' },
  'car.noParts':      { en: 'No parts yet', es: 'Sin recambios', zh: '暂无配件', de: 'Keine Ersatzteile', fr: 'Aucune pièce', ru: 'Запчастей нет' },

  // ══════════════════════════ RESUMEN ══════════════════════════
  'stats.title':        { en: 'Summary', es: 'Resumen', zh: '总览', de: 'Übersicht', fr: 'Résumé', ru: 'Сводка' },
  'stats.sub':          { en: 'Overall figures for your {n} vehicles', es: 'Estadísticas globales de tus {n} vehículos', zh: '你 {n} 辆车的总体数据', de: 'Gesamtzahlen für deine {n} Fahrzeuge', fr: 'Chiffres globaux de tes {n} véhicules', ru: 'Общие показатели по вашим машинам: {n}' },
  'stats.empty':        { en: 'You have no vehicles yet', es: 'No tienes vehículos registrados aún', zh: '你还没有登记任何车辆', de: 'Du hast noch keine Fahrzeuge erfasst', fr: 'Tu n’as encore aucun véhicule', ru: 'У вас ещё нет машин' },
  'stats.totalSpend':   { en: 'Total spend', es: 'Gasto total', zh: '总花费', de: 'Gesamtausgaben', fr: 'Dépense totale', ru: 'Всего потрачено' },
  'stats.totalKm':      { en: 'Total km', es: 'Km totales', zh: '总里程', de: 'Gesamt-km', fr: 'Km totaux', ru: 'Общий пробег' },
  'stats.overdue':      { en: 'Overdue maintenance', es: 'Mantenimientos vencidos', zh: '逾期保养', de: 'Überfällige Wartungen', fr: 'Entretiens en retard', ru: 'Просроченное ТО' },
  'stats.upcoming':     { en: 'Maintenance due soon', es: 'Mantenimientos próximos', zh: '即将到期的保养', de: 'Anstehende Wartungen', fr: 'Entretiens à prévoir', ru: 'Скорое ТО' },
  'stats.itvIssues':    { en: 'Inspection issues', es: 'ITV con problemas', zh: '年检问题', de: 'HU-Probleme', fr: 'Problèmes de contrôle', ru: 'Проблемы с техосмотром' },
  'stats.byVehicle':    { en: 'Spend by vehicle', es: 'Gasto por vehículo', zh: '各车花费', de: 'Ausgaben pro Fahrzeug', fr: 'Dépense par véhicule', ru: 'Расходы по машинам' },
  'stats.monthly':      { en: 'Monthly spend (all vehicles)', es: 'Gastos mensuales (todos los vehículos)', zh: '每月花费（全部车辆）', de: 'Monatliche Ausgaben (alle Fahrzeuge)', fr: 'Dépenses mensuelles (tous véhicules)', ru: 'Расходы по месяцам (все машины)' },
  'stats.distribution': { en: 'Spend split by vehicle', es: 'Distribución del gasto por vehículo', zh: '各车花费占比', de: 'Ausgabenverteilung nach Fahrzeug', fr: 'Répartition des dépenses par véhicule', ru: 'Распределение расходов по машинам' },
  'stats.costPerKm':    { en: 'Cost/km', es: 'Coste/km', zh: '每公里成本', de: 'Kosten/km', fr: 'Coût/km', ru: 'Цена/км' },
  'stats.attention':    { en: 'Needs attention', es: 'Requiere atención', zh: '需要处理', de: 'Braucht Aufmerksamkeit', fr: 'À surveiller', ru: 'Требует внимания' },
  'stats.allGood':      { en: 'Everything up to date', es: 'Todo al día', zh: '一切正常', de: 'Alles aktuell', fr: 'Tout est à jour', ru: 'Всё в порядке' },
  'stats.fleetCost':    { en: 'Whole fleet', es: 'Toda la flota', zh: '全部车辆', de: 'Gesamte Flotte', fr: 'Tout le parc', ru: 'Весь парк' },
  'wsh.spentHere':      { en: 'Spent here', es: 'Gastado aquí', zh: '在此花费', de: 'Hier ausgegeben', fr: 'Dépensé ici', ru: 'Потрачено здесь' },
  'wsh.history':        { en: 'Work history', es: 'Historial', zh: '维修记录', de: 'Verlauf', fr: 'Historique', ru: 'История работ' },
  'wsh.noHistory':      { en: 'No work logged here yet', es: 'Todavía no hay trabajos aquí', zh: '这里还没有记录', de: 'Noch keine Arbeiten erfasst', fr: 'Aucune intervention enregistrée', ru: 'Работ пока нет' },
  'wsh.pickOne':        { en: 'Pick a workshop to see its history', es: 'Elige un taller para ver su historial', zh: '选择一家维修店查看记录', de: 'Wähle eine Werkstatt für ihren Verlauf', fr: 'Choisis un garage pour voir son historique', ru: 'Выберите мастерскую, чтобы увидеть историю' },
  'wsh.jobs':           { en: '{n} jobs', es: '{n} trabajos', zh: '{n} 项工作', de: '{n} Arbeiten', fr: '{n} interventions', ru: 'Работ: {n}' },
  'adm.adminCount':     { en: '{n} admins', es: '{n} administradores', zh: '{n} 位管理员', de: '{n} Administratoren', fr: '{n} administrateurs', ru: 'Администраторов: {n}' },
  'adm.fleet':          { en: 'Whole fleet', es: 'Toda la flota', zh: '全部车辆', de: 'Gesamte Flotte', fr: 'Tout le parc', ru: 'Весь парк' },

  // ══════════════════════════ GASTOS ══════════════════════════
  'exp.monthly':  { en: 'Monthly spend (12 months)', es: 'Gastos mensuales (12 meses)', zh: '每月花费（12 个月）', de: 'Monatliche Ausgaben (12 Monate)', fr: 'Dépenses mensuelles (12 mois)', ru: 'Расходы по месяцам (12 месяцев)' },
  'exp.byCategory': { en: 'Breakdown by category', es: 'Desglose por categoría', zh: '按类别细分', de: 'Aufschlüsselung nach Kategorie', fr: 'Répartition par catégorie', ru: 'Разбивка по категориям' },
  'exp.empty':    { en: 'No expenses logged yet', es: 'Sin gastos registrados aún', zh: '暂无花费记录', de: 'Noch keine Ausgaben erfasst', fr: 'Aucune dépense enregistrée', ru: 'Расходов пока нет' },

  // ══════════════════════════ REPOSTAJES ══════════════════════════
  'fuelt.title':     { en: 'Refuelling', es: 'Repostajes', zh: '加油记录', de: 'Tankvorgänge', fr: 'Pleins', ru: 'Заправки' },
  'fuelt.empty':     { en: 'No refuelling logged', es: 'Sin repostajes', zh: '暂无加油记录', de: 'Keine Tankvorgänge', fr: 'Aucun plein', ru: 'Заправок нет' },
  'fuelt.new':       { en: 'New refuelling', es: 'Nuevo repostaje', zh: '新增加油', de: 'Neuer Tankvorgang', fr: 'Nouveau plein', ru: 'Новая заправка' },
  'fuelt.litres':    { en: 'Litres', es: 'Litros', zh: '升数', de: 'Liter', fr: 'Litres', ru: 'Литры' },
  'fuelt.pricePerL': { en: 'Price/litre', es: 'Precio/litro', zh: '每升价格', de: 'Preis/Liter', fr: 'Prix/litre', ru: 'Цена за литр' },
  'fuelt.fullTank':  { en: 'Full tank', es: 'Depósito lleno', zh: '加满', de: 'Volltank', fr: 'Plein complet', ru: 'Полный бак' },
  'fuelt.yesFull':   { en: 'Yes (full)', es: 'Sí (lleno)', zh: '是（加满）', de: 'Ja (voll)', fr: 'Oui (plein)', ru: 'Да (полный)' },
  'fuelt.partial':   { en: 'Partial', es: 'Parcial', zh: '部分', de: 'Teilweise', fr: 'Partiel', ru: 'Частично' },
  'fuelt.mode':      { en: 'Driving', es: 'Conducción', zh: '驾驶方式', de: 'Fahrweise', fr: 'Conduite', ru: 'Режим езды' },
  'fuelt.avg':       { en: 'Average', es: 'Consumo medio', zh: '平均油耗', de: 'Durchschnitt', fr: 'Consommation moyenne', ru: 'Средний расход' },
  'fuelt.added':     { en: 'Refuelling logged', es: 'Repostaje registrado', zh: '加油已记录', de: 'Tankvorgang erfasst', fr: 'Plein enregistré', ru: 'Заправка записана' },

  // ══════════════════════════ TAREAS ══════════════════════════
  'todo.new':      { en: 'New task', es: 'Nueva tarea', zh: '新建待办', de: 'Neue Aufgabe', fr: 'Nouvelle tâche', ru: 'Новая задача' },
  'todo.edit':     { en: 'Edit task', es: 'Editar tarea', zh: '编辑待办', de: 'Aufgabe bearbeiten', fr: 'Modifier la tâche', ru: 'Изменить задачу' },
  'todo.added':    { en: 'Task added', es: 'Tarea añadida', zh: '待办已添加', de: 'Aufgabe hinzugefügt', fr: 'Tâche ajoutée', ru: 'Задача добавлена' },
  'todo.empty':    { en: 'No pending tasks', es: 'Sin tareas pendientes', zh: '没有待办事项', de: 'Keine offenen Aufgaben', fr: 'Aucune tâche en attente', ru: 'Задач нет' },
  'todo.title':    { en: 'Task', es: 'Tarea', zh: '待办', de: 'Aufgabe', fr: 'Tâche', ru: 'Задача' },
  'todo.priority': { en: 'Priority', es: 'Prioridad', zh: '优先级', de: 'Priorität', fr: 'Priorité', ru: 'Приоритет' },
  'todo.high':     { en: 'High', es: 'Alta', zh: '高', de: 'Hoch', fr: 'Haute', ru: 'Высокий' },
  'todo.medium':   { en: 'Medium', es: 'Media', zh: '中', de: 'Mittel', fr: 'Moyenne', ru: 'Средний' },
  'todo.low':      { en: 'Low', es: 'Baja', zh: '低', de: 'Niedrig', fr: 'Basse', ru: 'Низкий' },
  'todo.confirm':  { en: 'Delete the task “{title}”?', es: '¿Eliminar la tarea «{title}»?', zh: '删除待办“{title}”？', de: 'Aufgabe „{title}“ löschen?', fr: 'Supprimer la tâche « {title} » ?', ru: 'Удалить задачу «{title}»?' },

  // ══════════════════════════ ITV ══════════════════════════
  'itv.title':      { en: 'Roadworthiness test', es: 'ITV', zh: '年检', de: 'Hauptuntersuchung', fr: 'Contrôle technique', ru: 'Техосмотр' },
  'itv.short':      { en: 'MOT', es: 'ITV', zh: '年检', de: 'HU', fr: 'CT', ru: 'ТО' },
  'itv.new':        { en: 'New test', es: 'Nueva ITV', zh: '新增年检', de: 'Neue HU', fr: 'Nouveau contrôle', ru: 'Новый техосмотр' },
  'itv.edit':       { en: 'Edit test', es: 'Editar ITV', zh: '编辑年检', de: 'HU bearbeiten', fr: 'Modifier le contrôle', ru: 'Изменить техосмотр' },
  'itv.empty':      { en: 'No test logged', es: 'Sin ITV registrada', zh: '暂无年检记录', de: 'Keine HU erfasst', fr: 'Aucun contrôle enregistré', ru: 'Техосмотр не записан' },
  'itv.confirm':    { en: 'Delete this test record?', es: '¿Eliminar este registro de ITV?', zh: '删除这条年检记录？', de: 'Diesen HU-Eintrag löschen?', fr: 'Supprimer cet enregistrement de contrôle ?', ru: 'Удалить эту запись техосмотра?' },
  'itv.inspection': { en: 'Test date', es: 'Fecha de inspección', zh: '检验日期', de: 'Prüfdatum', fr: 'Date du contrôle', ru: 'Дата осмотра' },
  'itv.expiry':     { en: 'Valid until', es: 'Caducidad', zh: '有效期至', de: 'Gültig bis', fr: 'Validité', ru: 'Действует до' },
  'itv.station':    { en: 'Test centre', es: 'Estación', zh: '检测站', de: 'Prüfstelle', fr: 'Centre', ru: 'Станция' },
  'itv.result':     { en: 'Result', es: 'Resultado', zh: '结果', de: 'Ergebnis', fr: 'Résultat', ru: 'Результат' },
  'itv.favorable':  { en: 'Pass', es: 'Favorable', zh: '合格', de: 'Bestanden', fr: 'Favorable', ru: 'Пройден' },
  'itv.unfavorable':{ en: 'Minor defects', es: 'Desfavorable', zh: '轻微缺陷', de: 'Geringe Mängel', fr: 'Défauts mineurs', ru: 'Мелкие дефекты' },
  'itv.negative':   { en: 'Fail', es: 'Negativa', zh: '不合格', de: 'Durchgefallen', fr: 'Refusé', ru: 'Не пройден' },
  'itv.defects':    { en: 'Defects', es: 'Defectos', zh: '缺陷', de: 'Mängel', fr: 'Défauts', ru: 'Дефекты' },
  'itv.noDefects':  { en: 'No defects', es: 'Sin defectos', zh: '无缺陷', de: 'Keine Mängel', fr: 'Aucun défaut', ru: 'Без дефектов' },
  'itv.minorNote':  { en: 'Minor defects — time allowed to repair', es: 'Defectos leves — plazo para reparar', zh: '轻微缺陷 — 有整改期限', de: 'Geringe Mängel — Frist zur Behebung', fr: 'Défauts mineurs — délai pour réparer', ru: 'Мелкие дефекты — есть срок на устранение' },
  'itv.repaired':   { en: 'Repaired', es: 'Reparado', zh: '已修复', de: 'Behoben', fr: 'Réparé', ru: 'Устранено' },
  'itv.pendingFix': { en: 'Repair pending', es: 'Pendiente reparar', zh: '待修复', de: 'Reparatur offen', fr: 'Réparation en attente', ru: 'Ожидает ремонта' },
  'itv.noExpiry':   { en: 'No expiry date', es: 'Sin fecha de caducidad', zh: '无到期日期', de: 'Kein Ablaufdatum', fr: 'Sans date d’expiration', ru: 'Без срока действия' },
  'itv.soon':       { en: 'Test due soon', es: 'ITV próxima', zh: '年检将到期', de: 'HU steht an', fr: 'Contrôle imminent', ru: 'Скоро техосмотр' },
  'itv.validUntil': { en: 'Valid until {date}', es: 'Válida hasta {date}', zh: '有效期至 {date}', de: 'Gültig bis {date}', fr: 'Valable jusqu’au {date}', ru: 'Действует до {date}' },
  'itv.expiresIn':  { en: 'Expires in {n} days', es: 'Caduca en {n} días', zh: '{n} 天后到期', de: 'Läuft in {n} Tagen ab', fr: 'Expire dans {n} jours', ru: 'Истекает через {n} дн.' },
  'itv.expiredAgo': { en: 'Expired {n} days ago', es: 'Caducada hace {n} días', zh: '已过期 {n} 天', de: 'Vor {n} Tagen abgelaufen', fr: 'Expiré il y a {n} jours', ru: 'Просрочен {n} дн. назад' },

  // ══════════════════════════ RECORDATORIOS ══════════════════════════
  'rem.title':     { en: 'Reminders', es: 'Recordatorios', zh: '提醒事项', de: 'Erinnerungen', fr: 'Rappels', ru: 'Напоминания' },
  'rem.new':       { en: 'New reminder', es: 'Nuevo recordatorio', zh: '新建提醒', de: 'Neue Erinnerung', fr: 'Nouveau rappel', ru: 'Новое напоминание' },
  'rem.edit':      { en: 'Edit reminder', es: 'Editar recordatorio', zh: '编辑提醒', de: 'Erinnerung bearbeiten', fr: 'Modifier le rappel', ru: 'Изменить напоминание' },
  'rem.empty':     { en: 'No reminders yet', es: 'Sin recordatorios todavía', zh: '还没有提醒', de: 'Noch keine Erinnerungen', fr: 'Aucun rappel', ru: 'Напоминаний нет' },
  'rem.emptyHint': { en: 'Create reminders for what you must not forget: insurance, roadworthiness tests, purchases…', es: 'Crea recordatorios para cosas que no puedes olvidar: seguros, ITVs, compras…', zh: '为不能忘记的事情创建提醒：保险、年检、采购……', de: 'Erstelle Erinnerungen für das, was du nicht vergessen darfst: Versicherung, HU, Einkäufe …', fr: 'Crée des rappels pour ce qu’il ne faut pas oublier : assurance, contrôle technique, achats…', ru: 'Создавайте напоминания о том, что нельзя забыть: страховка, техосмотр, покупки…' },
  'rem.thisWeek':  { en: 'This week', es: 'Esta semana', zh: '本周', de: 'Diese Woche', fr: 'Cette semaine', ru: 'На этой неделе' },
  'rem.fromCars':  { en: 'From your vehicles', es: 'De tus vehículos', zh: '来自你的车辆', de: 'Von deinen Fahrzeugen', fr: 'De tes véhicules', ru: 'От ваших машин' },
  'rem.next90':    { en: 'Next 90 days', es: 'Próximos 90 días', zh: '未来 90 天', de: 'Nächste 90 Tage', fr: 'Prochains 90 jours', ru: 'Ближайшие 90 дней' },
  'rem.emptyWeek': { en: 'Nothing this week', es: 'Nada esta semana', zh: '本周无事', de: 'Nichts diese Woche', fr: 'Rien cette semaine', ru: 'На этой неделе пусто' },
  'rem.emptyCars': { en: 'Vehicles are up to date', es: 'Los vehículos están al día', zh: '车辆状态正常', de: 'Fahrzeuge sind aktuell', fr: 'Les véhicules sont à jour', ru: 'С машинами всё в порядке' },
  'rem.overdueN':  { en: 'Overdue', es: 'Vencidos', zh: '已逾期', de: 'Überfällig', fr: 'En retard', ru: 'Просрочено' },
  'rem.done':      { en: 'Reminder completed', es: 'Recordatorio completado', zh: '提醒已完成', de: 'Erinnerung erledigt', fr: 'Rappel terminé', ru: 'Напоминание выполнено' },
  'rem.completed': { en: 'Completed', es: 'Completado', zh: '已完成', de: 'Erledigt', fr: 'Terminé', ru: 'Выполнено' },
  'rem.dueDate':   { en: 'Due date', es: 'Fecha', zh: '到期日', de: 'Fälligkeit', fr: 'Échéance', ru: 'Срок' },
  'rem.general':   { en: '— General (no vehicle) —', es: '— General (sin vehículo) —', zh: '— 通用（不指定车辆）—', de: '— Allgemein (ohne Fahrzeug) —', fr: '— Général (sans véhicule) —', ru: '— Общее (без машины) —' },
  'rem.tomorrow':  { en: 'Tomorrow', es: 'Mañana', zh: '明天', de: 'Morgen', fr: 'Demain', ru: 'Завтра' },
  'rem.today':     { en: 'Today', es: 'Hoy', zh: '今天', de: 'Heute', fr: 'Aujourd’hui', ru: 'Сегодня' },
  'rem.inDays':    { en: 'In {n} days', es: 'En {n} días', zh: '{n} 天后', de: 'In {n} Tagen', fr: 'Dans {n} jours', ru: 'Через {n} дн.' },
  'rem.agoDays':   { en: '{n} days ago', es: 'Hace {n} días', zh: '{n} 天前', de: 'Vor {n} Tagen', fr: 'Il y a {n} jours', ru: '{n} дн. назад' },
  'rem.confirm':   { en: 'Delete “{title}”?', es: '¿Eliminar «{title}»?', zh: '删除“{title}”？', de: '„{title}“ löschen?', fr: 'Supprimer « {title} » ?', ru: 'Удалить «{title}»?' },

  // ══════════════════════════ TALLERES ══════════════════════════
  'wsh.title':     { en: 'Workshops', es: 'Talleres', zh: '修理厂', de: 'Werkstätten', fr: 'Garages', ru: 'Мастерские' },
  'wsh.new':       { en: 'New workshop', es: 'Nuevo taller', zh: '新增修理厂', de: 'Neue Werkstatt', fr: 'Nouveau garage', ru: 'Новая мастерская' },
  'wsh.edit':      { en: 'Edit workshop', es: 'Editar taller', zh: '编辑修理厂', de: 'Werkstatt bearbeiten', fr: 'Modifier le garage', ru: 'Изменить мастерскую' },
  'wsh.add':       { en: 'Add workshop', es: 'Añadir taller', zh: '添加修理厂', de: 'Werkstatt hinzufügen', fr: 'Ajouter un garage', ru: 'Добавить мастерскую' },
  'wsh.added':     { en: 'Workshop added', es: 'Taller añadido', zh: '修理厂已添加', de: 'Werkstatt hinzugefügt', fr: 'Garage ajouté', ru: 'Мастерская добавлена' },
  'wsh.updated':   { en: 'Workshop updated', es: 'Taller actualizado', zh: '修理厂已更新', de: 'Werkstatt aktualisiert', fr: 'Garage mis à jour', ru: 'Мастерская обновлена' },
  'wsh.deleted':   { en: 'Workshop deleted', es: 'Taller eliminado', zh: '修理厂已删除', de: 'Werkstatt gelöscht', fr: 'Garage supprimé', ru: 'Мастерская удалена' },
  'wsh.empty':     { en: 'No workshops yet', es: 'No hay talleres registrados aún', zh: '还没有登记修理厂', de: 'Noch keine Werkstätten erfasst', fr: 'Aucun garage enregistré', ru: 'Мастерских пока нет' },
  'wsh.confirm':   { en: 'Delete this workshop?', es: '¿Eliminar este taller?', zh: '删除这家修理厂？', de: 'Diese Werkstatt löschen?', fr: 'Supprimer ce garage ?', ru: 'Удалить эту мастерскую?' },
  'wsh.loadError': { en: 'Error loading workshops: ', es: 'Error cargando talleres: ', zh: '加载修理厂出错：', de: 'Fehler beim Laden der Werkstätten: ', fr: 'Erreur de chargement des garages : ', ru: 'Ошибка загрузки мастерских: ' },
  'wsh.specialty': { en: 'Speciality', es: 'Especialidad', zh: '专长', de: 'Spezialgebiet', fr: 'Spécialité', ru: 'Специализация' },
  'wsh.rating':    { en: 'Rating', es: 'Valoración', zh: '评分', de: 'Bewertung', fr: 'Note', ru: 'Оценка' },
  'wsh.call':      { en: 'Call', es: 'Llamar', zh: '拨打电话', de: 'Anrufen', fr: 'Appeler', ru: 'Позвонить' },
  'wsh.addedBy':   { en: 'Added by {name}', es: 'Añadido por {name}', zh: '由 {name} 添加', de: 'Hinzugefügt von {name}', fr: 'Ajouté par {name}', ru: 'Добавил {name}' },

  // ══════════════════════════ GRUPOS ══════════════════════════
  'grp.title':        { en: 'Groups', es: 'Grupos', zh: '车友群', de: 'Gruppen', fr: 'Groupes', ru: 'Группы' },
  'grp.sub':          { en: 'Share your vehicles and chat with your people', es: 'Comparte tus vehículos y chatea con tu gente', zh: '分享你的车辆，和大家聊天', de: 'Teile deine Fahrzeuge und schreib mit deinen Leuten', fr: 'Partage tes véhicules et discute avec les tiens', ru: 'Делитесь машинами и общайтесь со своими' },
  'grp.none':         { en: 'You are not in any group yet', es: 'Aún no estás en ningún grupo', zh: '你还没有加入任何群', de: 'Du bist noch in keiner Gruppe', fr: 'Tu n’es dans aucun groupe', ru: 'Вы пока не состоите ни в одной группе' },
  'grp.noneHelpAdmin':{ en: 'Create a group to share vehicles and chat with your people.', es: 'Crea un grupo para compartir vehículos y chatear con tu gente.', zh: '创建一个群，分享车辆并和大家聊天。', de: 'Erstelle eine Gruppe, um Fahrzeuge zu teilen und zu schreiben.', fr: 'Crée un groupe pour partager des véhicules et discuter.', ru: 'Создайте группу, чтобы делиться машинами и общаться.' },
  'grp.noneHelpUser': { en: 'Request a group (an admin will approve it) or wait for an invitation.', es: 'Solicita crear un grupo (lo aprobará un admin) o espera a que alguien te invite.', zh: '申请创建一个群（需管理员批准），或等待别人邀请你。', de: 'Beantrage eine Gruppe (ein Admin genehmigt sie) oder warte auf eine Einladung.', fr: 'Demande la création d’un groupe (un admin l’approuvera) ou attends une invitation.', ru: 'Запросите группу (её одобрит админ) или дождитесь приглашения.' },
  'grp.new':          { en: 'New group', es: 'Nuevo grupo', zh: '新建群', de: 'Neue Gruppe', fr: 'Nouveau groupe', ru: 'Новая группа' },
  'grp.create':       { en: 'Create group', es: 'Crear grupo', zh: '创建群', de: 'Gruppe erstellen', fr: 'Créer un groupe', ru: 'Создать группу' },
  'grp.request':      { en: 'Request a group', es: 'Solicitar grupo', zh: '申请建群', de: 'Gruppe beantragen', fr: 'Demander un groupe', ru: 'Запросить группу' },
  'grp.created':      { en: 'Group created', es: 'Grupo creado', zh: '群已创建', de: 'Gruppe erstellt', fr: 'Groupe créé', ru: 'Группа создана' },
  'grp.deleted':      { en: 'Group deleted', es: 'Grupo eliminado', zh: '群已删除', de: 'Gruppe gelöscht', fr: 'Groupe supprimé', ru: 'Группа удалена' },
  'grp.requested':    { en: 'Request sent — an admin will review it', es: 'Solicitud enviada — un admin la revisará', zh: '申请已提交 — 管理员会审核', de: 'Antrag gesendet — ein Admin prüft ihn', fr: 'Demande envoyée — un admin va l’examiner', ru: 'Запрос отправлен — админ его рассмотрит' },
  'grp.waiting':      { en: 'Waiting', es: 'Esperando', zh: '等待中', de: 'Wartet', fr: 'En attente', ru: 'Ожидает' },
  'grp.open':         { en: 'Open', es: 'Abrir', zh: '打开', de: 'Öffnen', fr: 'Ouvrir', ru: 'Открыть' },
  'grp.youAreAdmin':  { en: '· You are the admin', es: '· Eres el admin', zh: '· 你是管理员', de: '· Du bist Admin', fr: '· Tu es l’admin', ru: '· Вы админ' },
  'grp.createdBy':    { en: 'Created by {name}', es: 'Creado por {name}', zh: '由 {name} 创建', de: 'Erstellt von {name}', fr: 'Créé par {name}', ru: 'Создал {name}' },
  'grp.invite':       { en: 'Invite', es: 'Invitar', zh: '邀请', de: 'Einladen', fr: 'Inviter', ru: 'Пригласить' },
  'grp.inviteNote':   { en: 'They will get an invitation and decide whether to join.', es: 'La persona recibirá una invitación y decide si entra o no.', zh: '对方会收到邀请，由他自己决定是否加入。', de: 'Die Person bekommt eine Einladung und entscheidet selbst.', fr: 'La personne recevra une invitation et décidera d’entrer ou non.', ru: 'Человек получит приглашение и сам решит, вступать ли.' },
  'grp.inviteSent':   { en: 'Invitation sent', es: 'Invitación enviada', zh: '邀请已发送', de: 'Einladung gesendet', fr: 'Invitation envoyée', ru: 'Приглашение отправлено' },
  'grp.inviteReject': { en: 'Invitation declined', es: 'Invitación rechazada', zh: '已拒绝邀请', de: 'Einladung abgelehnt', fr: 'Invitation refusée', ru: 'Приглашение отклонено' },
  'grp.invitedBy':    { en: '{name} invited you', es: 'Te ha invitado {name}', zh: '{name} 邀请了你', de: '{name} hat dich eingeladen', fr: '{name} t’a invité', ru: 'Вас пригласил {name}' },
  'grp.joined':       { en: 'You joined “{name}”', es: 'Te has unido a «{name}»', zh: '你加入了“{name}”', de: 'Du bist „{name}“ beigetreten', fr: 'Tu as rejoint « {name} »', ru: 'Вы вступили в «{name}»' },
  'grp.noOneToInvite':{ en: 'There is nobody else to invite', es: 'No hay nadie más a quien invitar', zh: '没有其他人可以邀请', de: 'Es gibt niemanden mehr zum Einladen', fr: 'Il n’y a personne d’autre à inviter', ru: 'Больше некого приглашать' },
  'grp.noVehicles':   { en: 'No member has vehicles yet', es: 'Ningún miembro tiene vehículos todavía', zh: '群成员还没有车辆', de: 'Noch hat kein Mitglied Fahrzeuge', fr: 'Aucun membre n’a encore de véhicule', ru: 'Ни у кого из участников пока нет машин' },
  'grp.noMessages':   { en: 'No messages yet. Be the first!', es: 'Sin mensajes aún. ¡Escribe el primero!', zh: '还没有消息，来发第一条吧！', de: 'Noch keine Nachrichten. Schreib die erste!', fr: 'Aucun message. Écris le premier !', ru: 'Сообщений пока нет. Напишите первое!' },
  'grp.writeMsg':     { en: 'Write a message', es: 'Escribe un mensaje', zh: '写一条消息', de: 'Nachricht schreiben', fr: 'Écris un message', ru: 'Написать сообщение' },
  'grp.members':      { en: 'Members', es: 'Miembros', zh: '成员', de: 'Mitglieder', fr: 'Membres', ru: 'Участники' },
  'grp.memberCount':  { en: '{n} members', es: '{n} miembros', zh: '{n} 位成员', de: '{n} Mitglieder', fr: '{n} membres', ru: 'Участников: {n}' },
  'grp.memberOne':    { en: '1 member', es: '1 miembro', zh: '1 位成员', de: '1 Mitglied', fr: '1 membre', ru: '1 участник' },
  'grp.invitePeople': { en: 'Invite people', es: 'Invitar gente', zh: '邀请成员', de: 'Leute einladen', fr: 'Inviter des gens', ru: 'Пригласить людей' },
  'grp.pickGroup':    { en: 'Pick a group to open its chat', es: 'Elige un grupo para abrir su chat', zh: '选择一个群组打开聊天', de: 'Wähle eine Gruppe für den Chat', fr: 'Choisis un groupe pour ouvrir le chat', ru: 'Выберите группу, чтобы открыть чат' },
  'grp.chat':         { en: 'Chat', es: 'Chat', zh: '聊天', de: 'Chat', fr: 'Discussion', ru: 'Чат' },
  'grp.removeMember': { en: 'Remove from the group?', es: '¿Eliminar del grupo?', zh: '将其移出群？', de: 'Aus der Gruppe entfernen?', fr: 'Retirer du groupe ?', ru: 'Удалить из группы?' },
  'grp.deleteConfirm':{ en: 'Delete this group and all of its messages?', es: '¿Eliminar este grupo y todos sus mensajes?', zh: '删除这个群及其全部消息？', de: 'Diese Gruppe und alle Nachrichten löschen?', fr: 'Supprimer ce groupe et tous ses messages ?', ru: 'Удалить эту группу и все её сообщения?' },

  // ══════════════════════════ ADMINISTRACIÓN ══════════════════════════
  'adm.title':        { en: 'Administration', es: 'Administración', zh: '后台管理', de: 'Verwaltung', fr: 'Administration', ru: 'Администрирование' },
  'adm.users':        { en: 'Users', es: 'Usuarios', zh: '用户', de: 'Benutzer', fr: 'Utilisateurs', ru: 'Пользователи' },
  'adm.admins':       { en: 'Administrators', es: 'Administradores', zh: '管理员', de: 'Administratoren', fr: 'Administrateurs', ru: 'Администраторы' },
  'adm.noAdmins':     { en: 'No administrators.', es: 'No hay administradores.', zh: '没有管理员。', de: 'Keine Administratoren.', fr: 'Aucun administrateur.', ru: 'Администраторов нет.' },
  'adm.noUsers':      { en: 'No regular users yet.', es: 'No hay usuarios normales todavía.', zh: '还没有普通用户。', de: 'Noch keine normalen Benutzer.', fr: 'Aucun utilisateur normal.', ru: 'Обычных пользователей пока нет.' },
  'adm.newUser':      { en: 'New user', es: 'Nuevo usuario', zh: '新建用户', de: 'Neuer Benutzer', fr: 'Nouvel utilisateur', ru: 'Новый пользователь' },
  'adm.editUser':     { en: 'Edit user', es: 'Editar usuario', zh: '编辑用户', de: 'Benutzer bearbeiten', fr: 'Modifier l’utilisateur', ru: 'Изменить пользователя' },
  'adm.userCreated':  { en: 'User created — they will be asked to change the PIN', es: 'Usuario creado — se le pedirá cambiar el PIN', zh: '用户已创建 — 首次登录需修改 PIN 码', de: 'Benutzer erstellt — die PIN muss geändert werden', fr: 'Utilisateur créé — il devra changer son PIN', ru: 'Пользователь создан — потребуется сменить PIN' },
  'adm.userUpdated':  { en: 'User updated', es: 'Usuario actualizado', zh: '用户已更新', de: 'Benutzer aktualisiert', fr: 'Utilisateur mis à jour', ru: 'Пользователь обновлён' },
  'adm.userDeleted':  { en: 'User deleted', es: 'Usuario eliminado', zh: '用户已删除', de: 'Benutzer gelöscht', fr: 'Utilisateur supprimé', ru: 'Пользователь удалён' },
  'adm.userExists':   { en: 'That username already exists', es: 'Ese usuario ya existe', zh: '该用户名已存在', de: 'Dieser Benutzername existiert bereits', fr: 'Cet identifiant existe déjà', ru: 'Такой пользователь уже есть' },
  'adm.deleteUser':   { en: 'Delete the user “{name}”?', es: '¿Eliminar al usuario «{name}»?', zh: '删除用户“{name}”？', de: 'Benutzer „{name}“ löschen?', fr: 'Supprimer l’utilisateur « {name} » ?', ru: 'Удалить пользователя «{name}»?' },
  'adm.role':         { en: 'Role', es: 'Rol', zh: '角色', de: 'Rolle', fr: 'Rôle', ru: 'Роль' },
  'adm.roleAdmin':    { en: 'Administrator', es: 'Administrador', zh: '管理员', de: 'Administrator', fr: 'Administrateur', ru: 'Администратор' },
  'adm.roleUser':     { en: 'User', es: 'Usuario', zh: '普通用户', de: 'Benutzer', fr: 'Utilisateur', ru: 'Пользователь' },
  'adm.pinPending':   { en: 'PIN pending', es: 'PIN pendiente', zh: '待改 PIN', de: 'PIN offen', fr: 'PIN à changer', ru: 'PIN не изменён' },
  'adm.pinNote':      { en: 'They will be asked to change the PIN on first sign-in.', es: 'Se le pedirá cambiar el PIN en su primer inicio de sesión.', zh: '首次登录时会要求修改 PIN 码。', de: 'Beim ersten Anmelden wird die PIN-Änderung verlangt.', fr: 'Il devra changer son PIN à la première connexion.', ru: 'При первом входе попросят сменить PIN-код.' },
  'adm.pinReset':     { en: 'PIN reset — they will have to change it when signing in', es: 'PIN restablecido — el usuario deberá cambiarlo al entrar', zh: 'PIN 码已重置 — 用户下次登录时须修改', de: 'PIN zurückgesetzt — sie muss beim Anmelden geändert werden', fr: 'PIN réinitialisé — il devra le changer en se connectant', ru: 'PIN сброшен — при входе его нужно будет сменить' },
  'adm.forcePin':     { en: 'Force a PIN change for “{name}”?', es: '¿Forzar cambio de PIN para «{name}»?', zh: '强制“{name}”修改 PIN 码？', de: 'PIN-Änderung für „{name}“ erzwingen?', fr: 'Forcer le changement de PIN pour « {name} » ?', ru: 'Заставить «{name}» сменить PIN-код?' },
  'adm.forcePinDone': { en: '{name} will be asked to change their PIN', es: 'Se pedirá a {name} que cambie su PIN', zh: '将要求 {name} 修改 PIN 码', de: '{name} wird zur PIN-Änderung aufgefordert', fr: '{name} devra changer son PIN', ru: '{name} попросят сменить PIN-код' },
  'adm.requests':     { en: 'Group requests', es: 'Solicitudes de grupo', zh: '建群申请', de: 'Gruppenanträge', fr: 'Demandes de groupe', ru: 'Запросы на группы' },
  'adm.noRequests':   { en: 'No pending requests', es: 'No hay solicitudes pendientes', zh: '没有待处理的申请', de: 'Keine offenen Anträge', fr: 'Aucune demande en attente', ru: 'Ожидающих запросов нет' },
  'adm.requestedBy':  { en: 'Requested by {name}', es: 'Solicitado por {name}', zh: '由 {name} 申请', de: 'Beantragt von {name}', fr: 'Demandé par {name}', ru: 'Запросил {name}' },
  'adm.approve':      { en: 'Approve', es: 'Aprobar', zh: '批准', de: 'Genehmigen', fr: 'Approuver', ru: 'Одобрить' },
  'adm.reject':       { en: 'Reject', es: 'Rechazar', zh: '拒绝', de: 'Ablehnen', fr: 'Refuser', ru: 'Отклонить' },
  'adm.approved':     { en: 'Group “{name}” approved', es: 'Grupo «{name}» aprobado', zh: '群“{name}”已批准', de: 'Gruppe „{name}“ genehmigt', fr: 'Groupe « {name} » approuvé', ru: 'Группа «{name}» одобрена' },
  'adm.rejectConfirm':{ en: 'Reject the request for the group “{name}”?', es: '¿Rechazar la solicitud del grupo «{name}»?', zh: '拒绝群“{name}”的申请？', de: 'Den Antrag für die Gruppe „{name}“ ablehnen?', fr: 'Refuser la demande du groupe « {name} » ?', ru: 'Отклонить запрос на группу «{name}»?' },
  'adm.stats':        { en: 'Statistics', es: 'Estadísticas', zh: '统计', de: 'Statistiken', fr: 'Statistiques', ru: 'Статистика' },
  'adm.perUser':      { en: 'Vehicles per user', es: 'Vehículos por usuario', zh: '每位用户的车辆', de: 'Fahrzeuge pro Benutzer', fr: 'Véhicules par utilisateur', ru: 'Машин на пользователя' },
  'adm.vehicleTypes': { en: 'Vehicle types', es: 'Tipos de vehículo', zh: '车辆类型', de: 'Fahrzeugtypen', fr: 'Types de véhicule', ru: 'Типы транспорта' },
  'adm.maintState':   { en: 'Maintenance status', es: 'Estado mantenimientos', zh: '保养状态', de: 'Wartungsstatus', fr: 'État des entretiens', ru: 'Состояние обслуживания' },
  'adm.totalKm':      { en: 'Total kilometres logged', es: 'Kilómetros totales registrados', zh: '累计登记里程', de: 'Erfasste Gesamtkilometer', fr: 'Kilomètres totaux enregistrés', ru: 'Всего записано километров' },
  'adm.upToDate':     { en: 'Up to date', es: 'Al día', zh: '正常', de: 'Aktuell', fr: 'À jour', ru: 'В норме' },
  'adm.upcoming':     { en: 'Due soon', es: 'Próximos', zh: '即将到期', de: 'Anstehend', fr: 'À prévoir', ru: 'Скоро' },
  'adm.upcomingShort':{ en: 'Soon', es: 'Próx.', zh: '将到期', de: 'Bald', fr: 'Bientôt', ru: 'Скоро' },

  // ══════════════════════════ DEMO ══════════════════════════
  'demo.banner':       { en: 'Demo mode — sample data. Change anything you like: nothing leaves your browser.', es: 'Modo demo — datos de ejemplo. Puedes tocar lo que quieras: nada sale de tu navegador.', zh: '演示模式 — 示例数据。随便改，什么都不会离开你的浏览器。', de: 'Demomodus — Beispieldaten. Ändere ruhig alles: nichts verlässt deinen Browser.', fr: 'Mode démo — données d’exemple. Touche à tout : rien ne quitte ton navigateur.', ru: 'Деморежим — примерные данные. Меняйте что угодно: ничего не покидает ваш браузер.' },
  'demo.bannerShort':  { en: 'Demo · sample data', es: 'Demo · datos de ejemplo', zh: '演示 · 示例数据', de: 'Demo · Beispieldaten', fr: 'Démo · données d’exemple', ru: 'Демо · примерные данные' },
  'demo.reset':        { en: 'Reset', es: 'Reiniciar', zh: '重置', de: 'Zurücksetzen', fr: 'Réinitialiser', ru: 'Сбросить' },
  'demo.resetConfirm': { en: 'Back to the sample data? Anything you changed in the demo will be lost.', es: '¿Volver a los datos de ejemplo? Se perderán los cambios que hayas hecho en la demo.', zh: '恢复示例数据？你在演示中所做的修改将会丢失。', de: 'Zurück zu den Beispieldaten? Deine Änderungen in der Demo gehen verloren.', fr: 'Revenir aux données d’exemple ? Tes modifications dans la démo seront perdues.', ru: 'Вернуть примерные данные? Изменения, сделанные в демоверсии, будут потеряны.' },
  'demo.resetDone':    { en: 'Demo reset', es: 'Demo reiniciada', zh: '演示已重置', de: 'Demo zurückgesetzt', fr: 'Démo réinitialisée', ru: 'Демоверсия сброшена' },
  'demo.exit':         { en: 'Leave the demo', es: 'Salir de la demo', zh: '退出演示', de: 'Demo verlassen', fr: 'Quitter la démo', ru: 'Выйти из демоверсии' },

  // ══════════════════════════ NOTIFICACIONES ══════════════════════════
  'notif.title':      { en: 'Notifications', es: 'Notificaciones', zh: '通知', de: 'Benachrichtigungen', fr: 'Notifications', ru: 'Уведомления' },
  'notif.empty':      { en: 'Everything is up to date', es: 'Todo al día', zh: '一切正常', de: 'Alles aktuell', fr: 'Tout est à jour', ru: 'Всё в порядке' },
  'notif.urgent':     { en: 'Urgent', es: 'Urgente', zh: '紧急', de: 'Dringend', fr: 'Urgent', ru: 'Срочно' },
  'notif.attention':  { en: 'Due soon', es: 'Atención', zh: '即将到期', de: 'Steht an', fr: 'À prévoir', ru: 'Скоро' },
  'notif.info':       { en: 'Info', es: 'Info', zh: '提示', de: 'Info', fr: 'Info', ru: 'Инфо' },
  'notif.dismiss':    { en: 'Hide for {n} days', es: 'Ocultar {n} días', zh: '隐藏 {n} 天', de: 'Für {n} Tage ausblenden', fr: 'Masquer {n} jours', ru: 'Скрыть на {n} дн.' },
  'notif.hidden':     { en: '{n} hidden', es: '{n} ocultas', zh: '已隐藏 {n} 条', de: '{n} ausgeblendet', fr: '{n} masquées', ru: 'Скрыто: {n}' },
  'notif.showHidden': { en: 'Show hidden', es: 'Ver ocultas', zh: '查看已隐藏', de: 'Ausgeblendete anzeigen', fr: 'Voir les masquées', ru: 'Показать скрытые' },
  'notif.hideHidden': { en: 'Hide them again', es: 'Volver a esconderlas', zh: '重新隐藏', de: 'Wieder ausblenden', fr: 'Les masquer à nouveau', ru: 'Снова скрыть' },
  'notif.backIn':     { en: 'Back in {n} d', es: 'Vuelve en {n} d', zh: '{n} 天后重现', de: 'Kommt in {n} T zurück', fr: 'Revient dans {n} j', ru: 'Вернётся через {n} дн.' },
  'notif.restore':    { en: 'Show again now', es: 'Mostrar ya', zh: '立即显示', de: 'Jetzt wieder anzeigen', fr: 'Réafficher maintenant', ru: 'Показать сейчас' },
  'notif.overdue':    { en: 'Overdue', es: 'Vencido', zh: '已逾期', de: 'Überfällig', fr: 'En retard', ru: 'Просрочено' },
  'notif.soon':       { en: 'Due soon', es: 'Próximo', zh: '即将到期', de: 'Steht an', fr: 'À prévoir', ru: 'Скоро' },
  'notif.kmPast':     { en: '{n} km past', es: '{n} km pasados', zh: '已超 {n} 公里', de: '{n} km überschritten', fr: '{n} km dépassés', ru: 'на {n} км больше' },
  'notif.kmLeft':     { en: 'in {n} km', es: 'en {n} km', zh: '还有 {n} 公里', de: 'in {n} km', fr: 'dans {n} km', ru: 'через {n} км' },
  'notif.daysAgo':    { en: '{n} days ago', es: 'hace {n} días', zh: '{n} 天前', de: 'vor {n} Tagen', fr: 'il y a {n} jours', ru: '{n} дн. назад' },
  'notif.daysLeft':   { en: 'in {n} days', es: 'en {n} días', zh: '还有 {n} 天', de: 'in {n} Tagen', fr: 'dans {n} jours', ru: 'через {n} дн.' },
  'notif.invitation': { en: 'Invitation to “{name}”', es: 'Invitación a «{name}»', zh: '“{name}”的邀请', de: 'Einladung zu „{name}“', fr: 'Invitation à « {name} »', ru: 'Приглашение в «{name}»' },
  'notif.goGroups':   { en: '{name} invited you · go to Groups', es: 'Te ha invitado {name} · ve a Grupos', zh: '{name} 邀请了你 · 前往车友群', de: '{name} hat dich eingeladen · zu Gruppen', fr: '{name} t’a invité · va dans Groupes', ru: 'Вас пригласил {name} · перейдите в Группы' },
  'notif.group':      { en: 'Group', es: 'Grupo', zh: '车友群', de: 'Gruppe', fr: 'Groupe', ru: 'Группа' },
  'notif.itvExpired': { en: 'Inspection expired', es: 'ITV caducada', zh: '年检已过期', de: 'HU abgelaufen', fr: 'Contrôle expiré', ru: 'Техосмотр просрочен' },
  'notif.itvSoon':    { en: 'Inspection due in {n} days', es: 'ITV caduca en {n} días', zh: '年检 {n} 天后到期', de: 'HU läuft in {n} Tagen ab', fr: 'Contrôle expire dans {n} jours', ru: 'Техосмотр истекает через {n} дн.' },
  'notif.reminder':   { en: 'Reminder', es: 'Recordatorio', zh: '提醒', de: 'Erinnerung', fr: 'Rappel', ru: 'Напоминание' },

  // ══════════════════════════ GESTOS ══════════════════════════
  'swipe.hint': { en: 'Swipe to change section', es: 'Desliza para cambiar de sección', zh: '左右滑动切换页面', de: 'Wischen, um den Bereich zu wechseln', fr: 'Balaie pour changer de section', ru: 'Проведите пальцем, чтобы сменить раздел' },

  // ══════════════════════════ TIPOS DE VEHÍCULO ══════════════════════════
  'veh.coche': { en: 'Car', es: 'Coche', zh: '汽车', de: 'Auto', fr: 'Voiture', ru: 'Автомобиль' },
  'veh.moto':  { en: 'Motorbike', es: 'Moto', zh: '摩托车', de: 'Motorrad', fr: 'Moto', ru: 'Мотоцикл' },

  // ══════════════════════════ COMBUSTIBLE ══════════════════════════
  'fuel.Gasolina':  { en: 'Petrol', es: 'Gasolina', zh: '汽油', de: 'Benzin', fr: 'Essence', ru: 'Бензин' },
  'fuel.Diésel':    { en: 'Diesel', es: 'Diésel', zh: '柴油', de: 'Diesel', fr: 'Diesel', ru: 'Дизель' },
  'fuel.Híbrido':   { en: 'Hybrid', es: 'Híbrido', zh: '混合动力', de: 'Hybrid', fr: 'Hybride', ru: 'Гибрид' },
  'fuel.Eléctrico': { en: 'Electric', es: 'Eléctrico', zh: '纯电动', de: 'Elektro', fr: 'Électrique', ru: 'Электро' },
  'fuel.GLP':       { en: 'LPG', es: 'GLP', zh: '液化石油气', de: 'Autogas', fr: 'GPL', ru: 'Газ' },

  // ══════════════════════════ TRANSMISIÓN ══════════════════════════
  'trans.Manual':     { en: 'Manual', es: 'Manual', zh: '手动', de: 'Schaltgetriebe', fr: 'Manuelle', ru: 'Механика' },
  'trans.Automático': { en: 'Automatic', es: 'Automático', zh: '自动', de: 'Automatik', fr: 'Automatique', ru: 'Автомат' },

  // ══════════════════════════ MODO DE CONDUCCIÓN ══════════════════════════
  'drive.ciudad':    { en: 'City', es: 'Ciudad', zh: '市区', de: 'Stadt', fr: 'Ville', ru: 'Город' },
  'drive.mixto':     { en: 'Mixed', es: 'Mixto', zh: '综合', de: 'Gemischt', fr: 'Mixte', ru: 'Смешанный' },
  'drive.carretera': { en: 'Highway', es: 'Carretera', zh: '公路', de: 'Landstraße', fr: 'Route', ru: 'Трасса' },

  // ══════════════════════════ MANTENIMIENTOS ══════════════════════════
  'maint.aceite':            { en: 'Engine oil', es: 'Aceite motor', zh: '机油', de: 'Motoröl', fr: 'Huile moteur', ru: 'Моторное масло' },
  'maint.filtro_aceite':     { en: 'Oil filter', es: 'Filtro de aceite', zh: '机油滤清器', de: 'Ölfilter', fr: 'Filtre à huile', ru: 'Масляный фильтр' },
  'maint.filtro_aire':       { en: 'Air filter', es: 'Filtro de aire', zh: '空气滤清器', de: 'Luftfilter', fr: 'Filtre à air', ru: 'Воздушный фильтр' },
  'maint.pastillas_del':     { en: 'Front brake pads', es: 'Pastillas freno del.', zh: '前刹车片', de: 'Bremsbeläge vorn', fr: 'Plaquettes avant', ru: 'Передние колодки' },
  'maint.pastillas_tras':    { en: 'Rear brake pads', es: 'Pastillas freno tras.', zh: '后刹车片', de: 'Bremsbeläge hinten', fr: 'Plaquettes arrière', ru: 'Задние колодки' },
  'maint.discos_freno':      { en: 'Brake discs', es: 'Discos de freno', zh: '刹车盘', de: 'Bremsscheiben', fr: 'Disques de frein', ru: 'Тормозные диски' },
  'maint.neumaticos':        { en: 'Tyres', es: 'Neumáticos', zh: '轮胎', de: 'Reifen', fr: 'Pneus', ru: 'Шины' },
  'maint.liquido_frenos':    { en: 'Brake fluid', es: 'Líquido de frenos', zh: '刹车油', de: 'Bremsflüssigkeit', fr: 'Liquide de frein', ru: 'Тормозная жидкость' },
  'maint.refrigerante':      { en: 'Coolant', es: 'Refrigerante', zh: '冷却液', de: 'Kühlmittel', fr: 'Liquide de refroidissement', ru: 'Охлаждающая жидкость' },
  'maint.bateria':           { en: 'Battery', es: 'Batería', zh: '电瓶', de: 'Batterie', fr: 'Batterie', ru: 'Аккумулятор' },
  'maint.embrague':          { en: 'Clutch', es: 'Embrague', zh: '离合器', de: 'Kupplung', fr: 'Embrayage', ru: 'Сцепление' },
  'maint.amortiguadores':    { en: 'Shock absorbers', es: 'Amortiguadores', zh: '减震器', de: 'Stoßdämpfer', fr: 'Amortisseurs', ru: 'Амортизаторы' },
  'maint.bujias':            { en: 'Spark plugs', es: 'Bujías', zh: '火花塞', de: 'Zündkerzen', fr: 'Bougies', ru: 'Свечи зажигания' },
  'maint.calentadores':      { en: 'Glow plugs', es: 'Calentadores', zh: '预热塞', de: 'Glühkerzen', fr: 'Bougies de préchauffage', ru: 'Свечи накаливания' },
  'maint.filtro_habitaculo': { en: 'Cabin filter', es: 'Filtro habitáculo', zh: '空调滤芯', de: 'Innenraumfilter', fr: 'Filtre habitacle', ru: 'Салонный фильтр' },
  'maint.correa_dist':       { en: 'Timing belt', es: 'Correa distribución', zh: '正时皮带', de: 'Zahnriemen', fr: 'Courroie de distribution', ru: 'Ремень ГРМ' },
  'maint.diferencial':       { en: 'Differential oil', es: 'Aceite diferencial', zh: '差速器油', de: 'Differentialöl', fr: 'Huile de différentiel', ru: 'Масло дифференциала' },
  'maint.caja_cambios':      { en: 'Gearbox oil', es: 'Aceite caja cambios', zh: '变速箱油', de: 'Getriebeöl', fr: 'Huile de boîte', ru: 'Масло КПП' },
  'maint.escobillas':        { en: 'Wiper blades', es: 'Escobillas limpiaparabrisas', zh: '雨刮片', de: 'Wischerblätter', fr: 'Balais d’essuie-glace', ru: 'Щётки стеклоочистителя' },
  'maint.cadena':            { en: 'Chain', es: 'Cadena', zh: '链条', de: 'Kette', fr: 'Chaîne', ru: 'Цепь' },
  'maint.kit_arrastre':      { en: 'Chain kit (sprockets)', es: 'Kit arrastre (piñón+corona)', zh: '链条套件（前后齿盘）', de: 'Kettenkit (Ritzel + Kranz)', fr: 'Kit chaîne (pignon + couronne)', ru: 'Комплект цепи (звёзды)' },
  'maint.liquido_embrague':  { en: 'Clutch fluid', es: 'Líquido embrague', zh: '离合器油', de: 'Kupplungsflüssigkeit', fr: 'Liquide d’embrayage', ru: 'Жидкость сцепления' },
  // ══════════════════════════ AÑADIDOS DE PANTALLA ══════════════════════════
  'common.unknown':  { en: 'unknown', es: 'desconocido', zh: '未知', de: 'unbekannt', fr: 'inconnu', ru: 'неизвестно' },
  'common.title':    { en: 'Title', es: 'Título', zh: '标题', de: 'Titel', fr: 'Titre', ru: 'Название' },
  'common.updated':  { en: 'Updated', es: 'Actualizado', zh: '已更新', de: 'Aktualisiert', fr: 'Mis à jour', ru: 'Обновлено' },
  'common.created':  { en: 'Created', es: 'Creado', zh: '已创建', de: 'Erstellt', fr: 'Créé', ru: 'Создано' },
  'common.deleted':  { en: 'Deleted', es: 'Eliminado', zh: '已删除', de: 'Gelöscht', fr: 'Supprimé', ru: 'Удалено' },

  'wsh.sub':         { en: 'Shared directory · {n} workshops', es: 'Directorio compartido · {n} talleres', zh: '共享目录 · {n} 家修理厂', de: 'Gemeinsames Verzeichnis · {n} Werkstätten', fr: 'Annuaire partagé · {n} garages', ru: 'Общий справочник · мастерских: {n}' },
  'wsh.namePh':      { en: 'e.g. Central Garage', es: 'Ej: Talleres Pérez', zh: '例如：中心修理厂', de: 'z. B. Werkstatt Müller', fr: 'Ex. : Garage Central', ru: 'Напр.: Автосервис Центр' },
  'wsh.phonePh':     { en: '612 345 678', es: '612 345 678', zh: '612 345 678', de: '612 345 678', fr: '612 345 678', ru: '612 345 678' },
  'wsh.addressPh':   { en: '15 Main Street', es: 'C/ Mayor 15', zh: '主街 15 号', de: 'Hauptstraße 15', fr: '15 rue Principale', ru: 'ул. Главная, 15' },
  'wsh.specialtyPh': { en: 'e.g. BMW, brakes, inspections…', es: 'Ej: BMW, frenos, ITV…', zh: '例如：宝马、刹车、年检…', de: 'z. B. BMW, Bremsen, HU…', fr: 'Ex. : BMW, freins, contrôle…', ru: 'Напр.: BMW, тормоза, техосмотр…' },
  'wsh.notesPh':     { en: 'Experience, prices…', es: 'Experiencia, precios…', zh: '经验、价格…', de: 'Erfahrung, Preise…', fr: 'Expérience, prix…', ru: 'Опыт, цены…' },
  'wsh.nameField':   { en: 'Workshop name', es: 'Nombre del taller', zh: '修理厂名称', de: 'Name der Werkstatt', fr: 'Nom du garage', ru: 'Название мастерской' },

  'rem.sub':         { en: '{n} pending', es: '{n} pendientes', zh: '{n} 项待处理', de: '{n} offen', fr: '{n} en attente', ru: 'Ожидают: {n}' },
  'rem.titlePh':     { en: 'e.g. Renew the insurance', es: 'Ej: Renovar el seguro', zh: '例如：续保', de: 'z. B. Versicherung verlängern', fr: 'Ex. : Renouveler l’assurance', ru: 'Напр.: продлить страховку' },
  'rem.notesPh':     { en: 'Details, links, anything', es: 'Detalles, enlaces, lo que sea', zh: '细节、链接，随便写', de: 'Details, Links, was auch immer', fr: 'Détails, liens, ce que tu veux', ru: 'Детали, ссылки, что угодно' },
  'rem.vehicleOpt':  { en: 'Vehicle (optional)', es: 'Vehículo (opcional)', zh: '车辆（可选）', de: 'Fahrzeug (optional)', fr: 'Véhicule (facultatif)', ru: 'Машина (необязательно)' },

  'todo.taskPh':     { en: 'e.g. Change the front pads', es: 'Ej: Cambiar las pastillas delanteras', zh: '例如：更换前刹车片', de: 'z. B. Bremsbeläge vorn wechseln', fr: 'Ex. : Changer les plaquettes avant', ru: 'Напр.: заменить передние колодки' },
  'todo.notesPh':    { en: 'Details, part numbers, where to buy…', es: 'Detalles, referencias, dónde comprarlas…', zh: '细节、零件号、在哪买…', de: 'Details, Teilenummern, wo kaufen…', fr: 'Détails, références, où acheter…', ru: 'Детали, артикулы, где купить…' },
  'todo.quickAdd':   { en: 'Quick task…', es: 'Añadir tarea rápida…', zh: '快速添加待办…', de: 'Schnelle Aufgabe…', fr: 'Tâche rapide…', ru: 'Быстрая задача…' },
  'todo.detailed':   { en: 'Task with details', es: 'Tarea con detalles', zh: '带详情的待办', de: 'Aufgabe mit Details', fr: 'Tâche détaillée', ru: 'Задача с деталями' },
  // ══════════════════════════ ESTADOS ══════════════════════════
  'status.ok':      { en: 'OK', es: 'OK', zh: '正常', de: 'OK', fr: 'OK', ru: 'ОК' },
  'status.warn':    { en: 'Due soon', es: 'Próximo', zh: '即将到期', de: 'Steht an', fr: 'À prévoir', ru: 'Скоро' },
  'status.overdue': { en: 'Overdue', es: 'Vencido', zh: '已逾期', de: 'Überfällig', fr: 'En retard', ru: 'Просрочено' },

  // ══════════════════════════ DETALLE · FORMULARIOS ══════════════════════════
  'car.logKmTitle':    { en: 'Log kilometres', es: 'Registrar kilómetros', zh: '记录里程', de: 'Kilometer eintragen', fr: 'Saisir le kilométrage', ru: 'Записать пробег' },
  'car.editVehicle':   { en: 'Edit vehicle', es: 'Editar vehículo', zh: '编辑车辆', de: 'Fahrzeug bearbeiten', fr: 'Modifier le véhicule', ru: 'Изменить машину' },
  'car.addPartTitle':  { en: 'Add part', es: 'Añadir recambio', zh: '添加配件', de: 'Ersatzteil hinzufügen', fr: 'Ajouter une pièce', ru: 'Добавить запчасть' },
  'car.lastChange':    { en: 'Last change (km)', es: 'Último cambio (km)', zh: '上次更换（公里）', de: 'Letzter Wechsel (km)', fr: 'Dernier changement (km)', ru: 'Прошлая замена (км)' },
  'car.lastChangeDate':{ en: 'Last change date', es: 'Fecha último cambio', zh: '上次更换日期', de: 'Datum letzter Wechsel', fr: 'Date du dernier changement', ru: 'Дата прошлой замены' },
  'car.nextChange':    { en: 'Next change (km)', es: 'Próximo cambio (km)', zh: '下次更换（公里）', de: 'Nächster Wechsel (km)', fr: 'Prochain changement (km)', ru: 'Следующая замена (км)' },
  'car.nextChangeDate':{ en: 'Next change date', es: 'Fecha próximo cambio', zh: '下次更换日期', de: 'Datum nächster Wechsel', fr: 'Date du prochain changement', ru: 'Дата следующей замены' },
  'car.costEur':       { en: 'Cost (€)', es: 'Coste (€)', zh: '费用（€）', de: 'Kosten (€)', fr: 'Coût (€)', ru: 'Стоимость (€)' },
  'car.maintNotesPh':  { en: 'Brand, workshop…', es: 'Marca, taller…', zh: '品牌、修理厂…', de: 'Marke, Werkstatt…', fr: 'Marque, garage…', ru: 'Марка, мастерская…' },
  'car.partNamePh':    { en: 'e.g. Oil filter', es: 'Ej: Filtro aceite', zh: '例如：机油滤清器', de: 'z. B. Ölfilter', fr: 'Ex. : Filtre à huile', ru: 'Напр.: масляный фильтр' },
  'car.partRefPh':     { en: 'e.g. OC 593/4', es: 'Ej: OC 593/4', zh: '例如：OC 593/4', de: 'z. B. OC 593/4', fr: 'Ex. : OC 593/4', ru: 'Напр.: OC 593/4' },
  'car.linkOptional':  { en: 'Link (optional)', es: 'Enlace (opcional)', zh: '链接（可选）', de: 'Link (optional)', fr: 'Lien (facultatif)', ru: 'Ссылка (необязательно)' },
  'car.recordDeleted': { en: 'Record deleted', es: 'Registro eliminado', zh: '记录已删除', de: 'Eintrag gelöscht', fr: 'Enregistrement supprimé', ru: 'Запись удалена' },
  'car.maintUpdated':  { en: 'Maintenance updated', es: 'Mantenimiento actualizado', zh: '保养已更新', de: 'Wartung aktualisiert', fr: 'Entretien mis à jour', ru: 'Обслуживание обновлено' },
  'car.partDeleted':   { en: 'Part deleted', es: 'Recambio eliminado', zh: '配件已删除', de: 'Ersatzteil gelöscht', fr: 'Pièce supprimée', ru: 'Запчасть удалена' },
  'car.export':        { en: 'Export', es: 'Exportar', zh: '导出', de: 'Exportieren', fr: 'Exporter', ru: 'Экспорт' },
  'car.statOk':        { en: 'Up to date', es: 'Al día', zh: '正常', de: 'Aktuell', fr: 'À jour', ru: 'В норме' },
  'car.statWarn':      { en: 'Due soon', es: 'Próximos', zh: '即将到期', de: 'Anstehend', fr: 'À prévoir', ru: 'Скоро' },
  'car.statOverdue':   { en: 'Overdue', es: 'Vencidos', zh: '已逾期', de: 'Überfällig', fr: 'En retard', ru: 'Просрочено' },
  'itv.severeNote':    { en: 'Serious defects — cannot be driven', es: 'Defectos graves — no puede circular', zh: '严重缺陷 — 不得上路', de: 'Schwere Mängel — darf nicht fahren', fr: 'Défauts graves — ne peut pas circuler', ru: 'Серьёзные дефекты — эксплуатация запрещена' },
  'itv.notRoadworthy': { en: 'Not roadworthy — failed', es: 'No apta — negativa', zh: '不合格 — 未通过', de: 'Nicht verkehrssicher — durchgefallen', fr: 'Non conforme — refusé', ru: 'Не допущен — не пройден' },
  'fuelt.noPartial':   { en: 'No (partial)', es: 'No (parcial)', zh: '否（部分）', de: 'Nein (teilweise)', fr: 'Non (partiel)', ru: 'Нет (частично)' },
  'car.element':  { en: 'Item', es: 'Elemento', zh: '项目', de: 'Position', fr: 'Élément', ru: 'Позиция' },
  'common.new':   { en: 'New', es: 'Nuevo', zh: '新建', de: 'Neu', fr: 'Nouveau', ru: 'Новое' },
  'fuelt.logIt':     { en: 'Log refuelling', es: 'Registrar repostaje', zh: '记录加油', de: 'Tankvorgang eintragen', fr: 'Enregistrer un plein', ru: 'Записать заправку' },
  'fuelt.perLitre':  { en: '€/L', es: '€/L', zh: '€/升', de: '€/L', fr: '€/L', ru: '€/л' },
  'fuelt.consum':    { en: 'Consumption', es: 'Consumo', zh: '油耗', de: 'Verbrauch', fr: 'Consommation', ru: 'Расход' },
  'fuelt.modeCol':   { en: 'Mode', es: 'Modo', zh: '模式', de: 'Modus', fr: 'Mode', ru: 'Режим' },
  'car.nextLabel':   { en: 'Next', es: 'Próximo', zh: '下次', de: 'Nächster', fr: 'Prochain', ru: 'Следующее' },
  'car.dateLabel':   { en: 'Date', es: 'Fecha', zh: '日期', de: 'Datum', fr: 'Date', ru: 'Дата' },
  'rem.reopened':    { en: 'Reminder reopened', es: 'Recordatorio reabierto', zh: '提醒已重新打开', de: 'Erinnerung wieder geöffnet', fr: 'Rappel rouvert', ru: 'Напоминание возобновлено' },
  'adm.overdueShort':{ en: 'Over.', es: 'Venc.', zh: '逾期', de: 'Überf.', fr: 'Retard', ru: 'Проср.' },
  // ══════════════════════════ NOMBRES DE LOS ACENTOS ══════════════════════════
  'accent.mandarina': { en: 'Tangerine', es: 'Mandarina', zh: '橘色', de: 'Mandarine', fr: 'Mandarine', ru: 'Мандарин' },
  'accent.turquesa':  { en: 'Turquoise', es: 'Turquesa', zh: '绿松石', de: 'Türkis', fr: 'Turquoise', ru: 'Бирюза' },
  'accent.manzana':   { en: 'Apple', es: 'Manzana', zh: '苹果绿', de: 'Apfelgrün', fr: 'Pomme', ru: 'Яблоко' },
  'accent.oro':       { en: 'Gold', es: 'Oro', zh: '金色', de: 'Gold', fr: 'Or', ru: 'Золото' },
  'accent.coral':     { en: 'Coral', es: 'Coral', zh: '珊瑚色', de: 'Koralle', fr: 'Corail', ru: 'Коралл' },
  'accent.frambuesa': { en: 'Raspberry', es: 'Frambuesa', zh: '覆盆子', de: 'Himbeere', fr: 'Framboise', ru: 'Малина' },
  'accent.purpura':   { en: 'Purple', es: 'Púrpura', zh: '紫色', de: 'Violett', fr: 'Violet', ru: 'Пурпур' },
  'accent.marfil':    { en: 'Ivory', es: 'Marfil', zh: '象牙白', de: 'Elfenbein', fr: 'Ivoire', ru: 'Слоновая кость' },

  // ══════════════════════════ GASTOS ══════════════════════════
  'exp.totalSpent': { en: 'Total spent', es: 'Total gastado', zh: '总支出', de: 'Insgesamt ausgegeben', fr: 'Total dépensé', ru: 'Всего потрачено' },
  'exp.thisYear':   { en: 'This year', es: 'Este año', zh: '今年', de: 'Dieses Jahr', fr: 'Cette année', ru: 'В этом году' },

  // ══════════════════════════ REPOSTAJES ══════════════════════════
  'fuelt.newTitle':    { en: 'New refuelling', es: 'Nuevo repostaje', zh: '新增加油', de: 'Neuer Tankvorgang', fr: 'Nouveau plein', ru: 'Новая заправка' },
  'fuelt.carKm':       { en: 'Vehicle odometer', es: 'Kilómetros del vehículo', zh: '车辆里程表', de: 'Kilometerstand', fr: 'Kilométrage du véhicule', ru: 'Пробег машины' },
  'fuelt.priceEur':    { en: 'Price/litre (€)', es: 'Precio/litro (€)', zh: '每升价格（€）', de: 'Preis/Liter (€)', fr: 'Prix/litre (€)', ru: 'Цена за литр (€)' },
  'fuelt.driveType':   { en: 'Driving type', es: 'Tipo de conducción', zh: '驾驶类型', de: 'Fahrweise', fr: 'Type de conduite', ru: 'Тип езды' },
  'fuelt.fullTankQ':   { en: 'Full tank', es: 'Depósito lleno', zh: '是否加满', de: 'Volltank', fr: 'Plein complet', ru: 'Полный бак' },
  'fuelt.totalSpent':  { en: 'Total spent', es: 'Total gastado', zh: '总支出', de: 'Insgesamt ausgegeben', fr: 'Total dépensé', ru: 'Всего потрачено' },
  'fuelt.totalLitres': { en: 'Total litres', es: 'Total litros', zh: '总升数', de: 'Liter gesamt', fr: 'Litres au total', ru: 'Всего литров' },
  'fuelt.avgPrice':    { en: 'Average €/L', es: 'Precio medio/L', zh: '平均每升价格', de: 'Durchschnitt €/L', fr: 'Prix moyen/L', ru: 'Средняя цена за литр' },
  'fuelt.deleted':     { en: 'Refuelling deleted', es: 'Repostaje eliminado', zh: '加油记录已删除', de: 'Tankvorgang gelöscht', fr: 'Plein supprimé', ru: 'Заправка удалена' },

  // ══════════════════════════ ITV ══════════════════════════
  'itv.stationName':    { en: 'Test centre name', es: 'Nombre de la estación', zh: '检测站名称', de: 'Name der Prüfstelle', fr: 'Nom du centre', ru: 'Название станции' },
  'itv.stationPh':      { en: 'e.g. City test centre', es: 'Ej: ITV Guadalhorce', zh: '例如：城市检测站', de: 'z. B. TÜV Süd', fr: 'Ex. : Centre Auto Sécurité', ru: 'Напр.: ГТО Центр' },
  'itv.defectsPh':      { en: 'Describe the defects…', es: 'Describe los defectos…', zh: '描述缺陷…', de: 'Mängel beschreiben…', fr: 'Décris les défauts…', ru: 'Опишите дефекты…' },
  'itv.repairedQ':      { en: 'Repaired and passed?', es: '¿Reparado y pasado?', zh: '已修复并通过？', de: 'Behoben und bestanden?', fr: 'Réparé et validé ?', ru: 'Устранено и пройдено?' },
  'itv.inspectionDate': { en: 'Inspection date', es: 'Fecha de inspección', zh: '检验日期', de: 'Prüfdatum', fr: 'Date d’inspection', ru: 'Дата осмотра' },
  'itv.expiryDate':     { en: 'Expiry date', es: 'Fecha de caducidad', zh: '到期日期', de: 'Ablaufdatum', fr: 'Date d’expiration', ru: 'Дата окончания' },
  'itv.soonWithDate':   { en: 'Expires in {n} days ({date})', es: 'Caduca en {n} días ({date})', zh: '{n} 天后到期（{date}）', de: 'Läuft in {n} Tagen ab ({date})', fr: 'Expire dans {n} jours ({date})', ru: 'Истекает через {n} дн. ({date})' },
  'itv.pendingWith':    { en: 'Repair pending — {what}', es: 'Pendiente reparar — {what}', zh: '待修复 — {what}', de: 'Reparatur offen — {what}', fr: 'Réparation en attente — {what}', ru: 'Ожидает ремонта — {what}' },
  'itv.checkDefects':   { en: 'check the defects', es: 'revisar defectos', zh: '检查缺陷', de: 'Mängel prüfen', fr: 'vérifier les défauts', ru: 'проверить дефекты' },
  'itv.soonTitle':      { en: 'Inspection due', es: 'ITV próxima', zh: '年检将到期', de: 'HU steht an', fr: 'Contrôle à prévoir', ru: 'Скоро техосмотр' },

  // ══════════════════════════ VARIOS ══════════════════════════
  'grp.you':         { en: '(you)', es: '(tú)', zh: '（你）', de: '(du)', fr: '(toi)', ru: '(вы)' },
  'todo.doneMsg':    { en: 'Task completed', es: 'Tarea completada', zh: '待办已完成', de: 'Aufgabe erledigt', fr: 'Tâche terminée', ru: 'Задача выполнена' },
  'todo.reopened':   { en: 'Task reopened', es: 'Tarea reabierta', zh: '待办已重新打开', de: 'Aufgabe wieder geöffnet', fr: 'Tâche rouverte', ru: 'Задача возобновлена' },
  'dash.loadError':  { en: 'Error loading vehicles: ', es: 'Error cargando vehículos: ', zh: '加载车辆出错：', de: 'Fehler beim Laden der Fahrzeuge: ', fr: 'Erreur de chargement des véhicules : ', ru: 'Ошибка загрузки машин: ' },
  'car.everyMonths': { en: ' / {n} months', es: ' / {n} meses', zh: ' / {n} 个月', de: ' / {n} Monate', fr: ' / {n} mois', ru: ' / {n} мес.' },
  'adm.userCount':   { en: '{n} users', es: '{n} usuarios', zh: '{n} 位用户', de: '{n} Benutzer', fr: '{n} utilisateurs', ru: 'Пользователей: {n}' },
  'adm.namePh':      { en: 'Full name', es: 'Nombre completo', zh: '姓名', de: 'Vollständiger Name', fr: 'Nom complet', ru: 'Полное имя' },
  'adm.userPh':      { en: 'username', es: 'nombre_usuario', zh: '用户名', de: 'benutzername', fr: 'identifiant', ru: 'имя_пользователя' },
  'notif.overdueBy': { en: 'Overdue by {n} days', es: 'Vencido hace {n} días', zh: '已逾期 {n} 天', de: 'Seit {n} Tagen überfällig', fr: 'En retard de {n} jours', ru: 'Просрочено на {n} дн.' },
  // ══════════════════════════ ERRORES ══════════════════════════
  'err.userNotFound': { en: 'User not found', es: 'Usuario no encontrado', zh: '未找到用户', de: 'Benutzer nicht gefunden', fr: 'Utilisateur introuvable', ru: 'Пользователь не найден' },
  'err.carNotFound':  { en: 'Vehicle not found', es: 'Vehículo no encontrado', zh: '未找到车辆', de: 'Fahrzeug nicht gefunden', fr: 'Véhicule introuvable', ru: 'Машина не найдена' },
  'err.wshNotFound':  { en: 'Workshop not found', es: 'Taller no encontrado', zh: '未找到修理厂', de: 'Werkstatt nicht gefunden', fr: 'Garage introuvable', ru: 'Мастерская не найдена' },
  'err.todoNotFound': { en: 'Task not found', es: 'Tarea no encontrada', zh: '未找到待办', de: 'Aufgabe nicht gefunden', fr: 'Tâche introuvable', ru: 'Задача не найдена' },
  'err.remNotFound':  { en: 'Reminder not found', es: 'Recordatorio no encontrado', zh: '未找到提醒', de: 'Erinnerung nicht gefunden', fr: 'Rappel introuvable', ru: 'Напоминание не найдено' },
  'err.itvNotFound':  { en: 'Test record not found', es: 'ITV no encontrada', zh: '未找到年检记录', de: 'HU-Eintrag nicht gefunden', fr: 'Contrôle introuvable', ru: 'Запись техосмотра не найдена' },

  // ══════════════════════════ INFORMES (PDF y Excel) ══════════════════════════
  'rep.generatedOn':   { en: 'Generated on {date}', es: 'Generado el {date}', zh: '生成于 {date}', de: 'Erstellt am {date}', fr: 'Généré le {date}', ru: 'Создано {date}' },
  'rep.overall':       { en: 'OVERALL STATUS', es: 'ESTADO GENERAL', zh: '总体状态', de: 'GESAMTZUSTAND', fr: 'ÉTAT GÉNÉRAL', ru: 'ОБЩЕЕ СОСТОЯНИЕ' },
  'rep.maintenance':   { en: 'MAINTENANCE', es: 'MANTENIMIENTOS', zh: '保养记录', de: 'WARTUNGEN', fr: 'ENTRETIENS', ru: 'ОБСЛУЖИВАНИЕ' },
  'rep.fuel':          { en: 'REFUELLING AND CONSUMPTION', es: 'REPOSTAJES Y CONSUMO', zh: '加油与油耗', de: 'TANKEN UND VERBRAUCH', fr: 'PLEINS ET CONSOMMATION', ru: 'ЗАПРАВКИ И РАСХОД' },
  'rep.todos':         { en: 'PENDING TASKS', es: 'TAREAS PENDIENTES', zh: '待办事项', de: 'OFFENE AUFGABEN', fr: 'TÂCHES EN ATTENTE', ru: 'ЗАДАЧИ' },
  'rep.parts':         { en: 'PARTS', es: 'RECAMBIOS', zh: '配件', de: 'ERSATZTEILE', fr: 'PIÈCES', ru: 'ЗАПЧАСТИ' },
  'rep.kmHistory':     { en: 'ODOMETER HISTORY', es: 'HISTORIAL DE KILÓMETROS', zh: '里程历史', de: 'KILOMETERVERLAUF', fr: 'HISTORIQUE DU KILOMÉTRAGE', ru: 'ИСТОРИЯ ПРОБЕГА' },
  'rep.itv':           { en: 'ROADWORTHINESS TESTS', es: 'INSPECCIONES (ITV)', zh: '年检记录', de: 'HAUPTUNTERSUCHUNGEN', fr: 'CONTRÔLES TECHNIQUES', ru: 'ТЕХОСМОТРЫ' },
  'rep.expenses':      { en: 'EXPENSES', es: 'GASTOS', zh: '花费', de: 'AUSGABEN', fr: 'DÉPENSES', ru: 'РАСХОДЫ' },
  'rep.summary':       { en: 'SUMMARY', es: 'RESUMEN', zh: '总览', de: 'ÜBERSICHT', fr: 'RÉSUMÉ', ru: 'СВОДКА' },
  'rep.noRecords':     { en: 'No records', es: 'Sin registros', zh: '暂无记录', de: 'Keine Einträge', fr: 'Aucun enregistrement', ru: 'Записей нет' },
  'rep.noInspections': { en: 'No inspections logged', es: 'Sin inspecciones registradas', zh: '暂无年检记录', de: 'Keine Untersuchungen erfasst', fr: 'Aucun contrôle enregistré', ru: 'Осмотров не записано' },
  'rep.totalSpend':    { en: 'Total spend', es: 'Gasto total', zh: '总花费', de: 'Gesamtausgaben', fr: 'Dépense totale', ru: 'Всего потрачено' },
  'rep.totalLitres':   { en: 'Total litres', es: 'Litros totales', zh: '总升数', de: 'Liter gesamt', fr: 'Litres au total', ru: 'Всего литров' },
  'rep.avgPrice':      { en: 'Average €/L', es: 'Precio medio/L', zh: '平均每升价格', de: 'Durchschnitt €/L', fr: 'Prix moyen/L', ru: 'Средняя цена за литр' },
  'rep.pendingCount':  { en: '{n} tasks to do on this vehicle', es: '{n} tareas por hacer en este vehículo', zh: '这辆车有 {n} 项待办', de: '{n} offene Aufgaben an diesem Fahrzeug', fr: '{n} tâches à faire sur ce véhicule', ru: 'По этой машине задач: {n}' },
  'rep.completed':     { en: 'Completed', es: 'Completada', zh: '已完成', de: 'Erledigt', fr: 'Terminée', ru: 'Выполнена' },
  'rep.pending':       { en: 'Pending', es: 'Pendiente', zh: '待处理', de: 'Offen', fr: 'En attente', ru: 'Ожидает' },
  'rep.year':          { en: 'Year', es: 'Año', zh: '年份', de: 'Baujahr', fr: 'Année', ru: 'Год' },
  'rep.consumption':   { en: 'Consumption', es: 'Consumo', zh: '油耗', de: 'Verbrauch', fr: 'Consommation', ru: 'Расход' },
  'rep.mode':          { en: 'Mode', es: 'Modo', zh: '模式', de: 'Modus', fr: 'Mode', ru: 'Режим' },
  'rep.priority':      { en: 'Priority', es: 'Prioridad', zh: '优先级', de: 'Priorität', fr: 'Priorité', ru: 'Приоритет' },
  'rep.result':        { en: 'Result', es: 'Resultado', zh: '结果', de: 'Ergebnis', fr: 'Résultat', ru: 'Результат' },
  'rep.station':       { en: 'Test centre', es: 'Estación', zh: '检测站', de: 'Prüfstelle', fr: 'Centre', ru: 'Станция' },
  'rep.defects':       { en: 'Defects', es: 'Defectos', zh: '缺陷', de: 'Mängel', fr: 'Défauts', ru: 'Дефекты' },
  'rep.validUntil':    { en: 'Valid until {date}', es: 'Válida hasta {date}', zh: '有效期至 {date}', de: 'Gültig bis {date}', fr: 'Valable jusqu’au {date}', ru: 'Действует до {date}' },
  'rep.expiresIn':     { en: 'Expires in {n} days', es: 'Caduca en {n} días', zh: '{n} 天后到期', de: 'Läuft in {n} Tagen ab', fr: 'Expire dans {n} jours', ru: 'Истекает через {n} дн.' },
  'rep.expiredAgo':    { en: 'Expired {n} days ago', es: 'Caducada hace {n} días', zh: '已过期 {n} 天', de: 'Vor {n} Tagen abgelaufen', fr: 'Expiré il y a {n} jours', ru: 'Просрочен {n} дн. назад' },
  'rep.noData':        { en: 'no data', es: 'sin datos', zh: '暂无数据', de: 'keine Daten', fr: 'aucune donnée', ru: 'нет данных' },
  'rep.sheetVehicle':  { en: 'Vehicle', es: 'Vehículo', zh: '车辆', de: 'Fahrzeug', fr: 'Véhicule', ru: 'Машина' },
  'rep.vehicleData':  { en: 'VEHICLE DETAILS', es: 'DATOS DEL VEHÍCULO', zh: '车辆信息', de: 'FAHRZEUGDATEN', fr: 'DONNÉES DU VÉHICULE', ru: 'ДАННЫЕ МАШИНЫ' },
  'rep.maintState':   { en: 'MAINTENANCE STATUS', es: 'ESTADO DE MANTENIMIENTOS', zh: '保养状态', de: 'WARTUNGSSTATUS', fr: 'ÉTAT DES ENTRETIENS', ru: 'СОСТОЯНИЕ ОБСЛУЖИВАНИЯ' },
  'rep.economic':     { en: 'FINANCIAL SUMMARY', es: 'RESUMEN ECONÓMICO', zh: '财务总览', de: 'FINANZÜBERSICHT', fr: 'RÉSUMÉ FINANCIER', ru: 'ФИНАНСОВАЯ СВОДКА' },
  'rep.totalSpent':   { en: 'TOTAL SPENT', es: 'TOTAL GASTADO', zh: '总支出', de: 'INSGESAMT AUSGEGEBEN', fr: 'TOTAL DÉPENSÉ', ru: 'ВСЕГО ПОТРАЧЕНО' },
  'rep.currentState': { en: 'Current status', es: 'Estado actual', zh: '当前状态', de: 'Aktueller Zustand', fr: 'État actuel', ru: 'Текущее состояние' },
  'rep.currentKm':    { en: 'Current kilometres', es: 'Kilómetros actuales', zh: '当前里程', de: 'Aktueller km-Stand', fr: 'Kilométrage actuel', ru: 'Текущий пробег' },
  'rep.costEur':      { en: 'Cost (€)', es: 'Coste (€)', zh: '费用（€）', de: 'Kosten (€)', fr: 'Coût (€)', ru: 'Стоимость (€)' },
  'rep.costPerKm':    { en: 'Cost per kilometre', es: 'Coste por kilómetro', zh: '每公里成本', de: 'Kosten pro Kilometer', fr: 'Coût par kilomètre', ru: 'Стоимость за километр' },
  'rep.lastKm':       { en: 'Last km', es: 'Último km', zh: '上次里程', de: 'Letzter km', fr: 'Dernier km', ru: 'Прошлый км' },
  'rep.nextKm':       { en: 'Next km', es: 'Próximo km', zh: '下次里程', de: 'Nächster km', fr: 'Prochain km', ru: 'Следующий км' },
  'rep.lastDate':     { en: 'Last date', es: 'Fecha último', zh: '上次日期', de: 'Letztes Datum', fr: 'Date précédente', ru: 'Прошлая дата' },
  'rep.nextDate':     { en: 'Next date', es: 'Fecha próximo', zh: '下次日期', de: 'Nächstes Datum', fr: 'Date prochaine', ru: 'Следующая дата' },
  'rep.avgPriceCol':  { en: 'Average price', es: 'Precio medio', zh: '平均价格', de: 'Durchschnittspreis', fr: 'Prix moyen', ru: 'Средняя цена' },
  'rep.priceCol':     { en: 'Price €/L', es: 'Precio €/L', zh: '价格 €/升', de: 'Preis €/L', fr: 'Prix €/L', ru: 'Цена €/л' },
  'rep.refuelCount':  { en: 'Total refuellings', es: 'Repostajes totales', zh: '加油次数', de: 'Tankvorgänge gesamt', fr: 'Pleins au total', ru: 'Всего заправок' },
  'rep.upcoming':     { en: 'Due soon', es: 'Próximos', zh: '即将到期', de: 'Anstehend', fr: 'À prévoir', ru: 'Скоро' },
  'rep.doneCol':      { en: 'Completed', es: 'Completado', zh: '已完成', de: 'Erledigt', fr: 'Terminé', ru: 'Выполнено' },
  'rep.titleCol':     { en: 'Title', es: 'Título', zh: '标题', de: 'Titel', fr: 'Titre', ru: 'Название' },
  'rep.itvPending':   { en: 'MINOR DEFECTS — pending', es: 'DESFAVORABLE — Pendiente', zh: '轻微缺陷 — 待处理', de: 'GERINGE MÄNGEL — offen', fr: 'DÉFAUTS MINEURS — en attente', ru: 'МЕЛКИЕ ДЕФЕКТЫ — не устранены' },
  'rep.itvExpiredCaps': { en: 'EXPIRED {n} days ago', es: 'CADUCADA hace {n} días', zh: '已过期 {n} 天', de: 'SEIT {n} Tagen ABGELAUFEN', fr: 'EXPIRÉ il y a {n} jours', ru: 'ПРОСРОЧЕН {n} дн. назад' },
  // ══════════════════════════ ÚLTIMA TANDA ══════════════════════════
  'common.join':       { en: 'Join', es: 'Unirme', zh: '加入', de: 'Beitreten', fr: 'Rejoindre', ru: 'Вступить' },
  'common.accept':     { en: 'Accept', es: 'Aceptar', zh: '接受', de: 'Annehmen', fr: 'Accepter', ru: 'Принять' },
  'common.type':       { en: 'Type', es: 'Tipo', zh: '类型', de: 'Typ', fr: 'Type', ru: 'Тип' },
  'common.pending':    { en: 'Pending', es: 'Pendientes', zh: '待处理', de: 'Offen', fr: 'En attente', ru: 'Ожидают' },
  'common.completed':  { en: 'Completed', es: 'Completadas', zh: '已完成', de: 'Erledigt', fr: 'Terminées', ru: 'Выполнены' },
  'common.vehCount':   { en: '{n} vehicles', es: '{n} vehículos', zh: '{n} 辆车', de: '{n} Fahrzeuge', fr: '{n} véhicules', ru: 'машин: {n}' },
  'common.vehCount1':  { en: '1 vehicle', es: '1 vehículo', zh: '1 辆车', de: '1 Fahrzeug', fr: '1 véhicule', ru: '1 машина' },
  'common.yes':        { en: 'Yes', es: 'Sí', zh: '是', de: 'Ja', fr: 'Oui', ru: 'Да' },
  'common.no':         { en: 'No', es: 'No', zh: '否', de: 'Nein', fr: 'Non', ru: 'Нет' },

  'adm.reqRejected':   { en: 'Request rejected', es: 'Solicitud rechazada', zh: '申请已拒绝', de: 'Antrag abgelehnt', fr: 'Demande refusée', ru: 'Запрос отклонён' },
  'adm.resetPinFor':   { en: 'Set a new PIN for {name}.', es: 'Establece un PIN nuevo para {name}.', zh: '为 {name} 设置新的 PIN 码。', de: 'Neue PIN für {name} festlegen.', fr: 'Définis un nouveau PIN pour {name}.', ru: 'Задайте новый PIN-код для {name}.' },
  'adm.resetPinNote':  { en: 'They will be asked to change it next time they sign in.', es: 'Se le pedirá cambiarlo la próxima vez que entre.', zh: '下次登录时会要求其修改。', de: 'Beim nächsten Anmelden wird die Änderung verlangt.', fr: 'Il devra le changer à sa prochaine connexion.', ru: 'При следующем входе его попросят сменить.' },
  'adm.reqHelp':       { en: 'Group requests waiting for approval. Once approved, whoever asked becomes the group admin and can invite others.', es: 'Solicitudes de grupo pendientes de aprobación. Al aprobar, el solicitante se convierte en administrador del grupo y puede invitar a más gente.', zh: '等待批准的建群申请。批准后，申请人将成为群管理员，并可以邀请其他人。', de: 'Gruppenanträge, die auf Genehmigung warten. Nach der Genehmigung wird die anfragende Person Gruppenadministrator und kann andere einladen.', fr: 'Demandes de groupe en attente d’approbation. Une fois approuvée, le demandeur devient administrateur du groupe et peut inviter d’autres personnes.', ru: 'Запросы на группы, ожидающие одобрения. После одобрения автор запроса становится администратором группы и может приглашать других.' },
  'adm.overdueMaint':  { en: 'Overdue maint.', es: 'Mant. vencidos', zh: '逾期保养', de: 'Überf. Wartung', fr: 'Entret. en retard', ru: 'Просроч. ТО' },
  'adm.overdue':       { en: 'Overdue', es: 'Vencidos', zh: '已逾期', de: 'Überfällig', fr: 'En retard', ru: 'Просрочено' },

  'car.lastLabel':     { en: 'Last', es: 'Último', zh: '上次', de: 'Letzter', fr: 'Dernier', ru: 'Прошлое' },

  'grp.invPending':    { en: 'Pending invitations ({n})', es: 'Invitaciones pendientes ({n})', zh: '待处理邀请（{n}）', de: 'Offene Einladungen ({n})', fr: 'Invitations en attente ({n})', ru: 'Ожидающие приглашения ({n})' },
  'grp.invitations':   { en: 'Invitations ({n})', es: 'Invitaciones ({n})', zh: '邀请（{n}）', de: 'Einladungen ({n})', fr: 'Invitations ({n})', ru: 'Приглашения ({n})' },
  'grp.vehiclesOf':    { en: 'Vehicles of {name}', es: 'Vehículos de {name}', zh: '{name} 的车辆', de: 'Fahrzeuge von {name}', fr: 'Véhicules de {name}', ru: 'Машины: {name}' },
  'grp.requestHelp':   { en: 'An administrator will review your request. If it is approved you become the group admin and can invite anyone you like.', es: 'Tu solicitud la revisará un administrador. Si la aprueba, serás el admin del grupo y podrás invitar a quien quieras.', zh: '管理员会审核你的申请。批准后你将成为群管理员，可以随意邀请他人。', de: 'Ein Administrator prüft deinen Antrag. Wird er genehmigt, wirst du Gruppenadministrator und kannst einladen, wen du willst.', fr: 'Un administrateur examinera ta demande. Si elle est approuvée, tu deviendras l’admin du groupe et pourras inviter qui tu veux.', ru: 'Ваш запрос рассмотрит администратор. Если его одобрят, вы станете админом группы и сможете приглашать кого угодно.' },

  'itv.defectsFound':  { en: 'Defects found', es: 'Defectos encontrados', zh: '发现的缺陷', de: 'Festgestellte Mängel', fr: 'Défauts constatés', ru: 'Обнаруженные дефекты' },
  'itv.inspectedOn':   { en: 'Inspection: {date}', es: 'Inspección: {date}', zh: '检验：{date}', de: 'Prüfung: {date}', fr: 'Contrôle : {date}', ru: 'Осмотр: {date}' },
  'itv.expiredTitle':  { en: 'Inspection expired', es: 'ITV caducada', zh: '年检已过期', de: 'HU abgelaufen', fr: 'Contrôle expiré', ru: 'Техосмотр просрочен' },
  'itv.failedWith':    { en: 'Failed — {what}', es: 'No apta — {what}', zh: '未通过 — {what}', de: 'Nicht bestanden — {what}', fr: 'Refusé — {what}', ru: 'Не пройден — {what}' },

  'rem.createFirst':   { en: 'Create your first reminder', es: 'Crear primer recordatorio', zh: '创建第一条提醒', de: 'Erste Erinnerung anlegen', fr: 'Créer le premier rappel', ru: 'Создать первое напоминание' },
  'rem.generalShort':  { en: 'General', es: 'General', zh: '通用', de: 'Allgemein', fr: 'Général', ru: 'Общее' },

  'todo.help':         { en: 'Add things you need to do to this vehicle', es: 'Añade cosas que tengas que hacer al vehículo', zh: '添加这辆车需要处理的事项', de: 'Trag ein, was an diesem Fahrzeug zu tun ist', fr: 'Ajoute ce que tu dois faire sur ce véhicule', ru: 'Добавьте, что нужно сделать с этой машиной' },

  'fuelt.avgConsum':   { en: 'Average consumption', es: 'Consumo medio', zh: '平均油耗', de: 'Durchschnittsverbrauch', fr: 'Consommation moyenne', ru: 'Средний расход' },

  // ── Informes ──
  'rep.vehicleReport': { en: 'VEHICLE REPORT', es: 'INFORME DE VEHÍCULO', zh: '车辆报告', de: 'FAHRZEUGBERICHT', fr: 'RAPPORT DU VÉHICULE', ru: 'ОТЧЁТ ПО МАШИНЕ' },
  'rep.reportOf':      { en: 'REPORT — {name}', es: 'INFORME — {name}', zh: '报告 — {name}', de: 'BERICHT — {name}', fr: 'RAPPORT — {name}', ru: 'ОТЧЁТ — {name}' },
  'rep.currentKmBox':  { en: 'Current km', es: 'Km actuales', zh: '当前里程', de: 'Aktuelle km', fr: 'Km actuels', ru: 'Текущий пробег' },
  'rep.kmUnit':        { en: 'kilometres', es: 'kilómetros', zh: '公里', de: 'Kilometer', fr: 'kilomètres', ru: 'километры' },
  'rep.maintOk':       { en: 'Maintenance OK', es: 'Mantenimientos OK', zh: '保养正常', de: 'Wartung OK', fr: 'Entretiens OK', ru: 'Обслуживание в норме' },
  'rep.checkSoon':     { en: 'Service due soon', es: 'Revisión pronto', zh: '即将需要保养', de: 'Bald zur Wartung', fr: 'Révision bientôt', ru: 'Скоро обслуживание' },
  'rep.urgent':        { en: 'Urgent action', es: 'Acción urgente', zh: '需紧急处理', de: 'Dringender Handlungsbedarf', fr: 'Action urgente', ru: 'Нужны срочные меры' },
  'rep.overdueCaps':   { en: 'OVERDUE', es: 'VENCIDOS', zh: '已逾期', de: 'ÜBERFÄLLIG', fr: 'EN RETARD', ru: 'ПРОСРОЧЕНО' },
  'rep.itvSection':    { en: 'ROADWORTHINESS TEST', es: 'INSPECCIÓN TÉCNICA (ITV)', zh: '车辆年检', de: 'HAUPTUNTERSUCHUNG', fr: 'CONTRÔLE TECHNIQUE', ru: 'ТЕХНИЧЕСКИЙ ОСМОТР' },
  'rep.itvHistory':    { en: 'TEST HISTORY', es: 'HISTORIAL ITV', zh: '年检历史', de: 'HU-VERLAUF', fr: 'HISTORIQUE DES CONTRÔLES', ru: 'ИСТОРИЯ ТЕХОСМОТРОВ' },
  'rep.itvCount':      { en: 'Records: {n} | Last inspection: {date}', es: 'Total registros: {n} | Última inspección: {date}', zh: '记录数：{n} ｜ 最近检验：{date}', de: 'Einträge: {n} | Letzte Prüfung: {date}', fr: 'Enregistrements : {n} | Dernier contrôle : {date}', ru: 'Записей: {n} | Последний осмотр: {date}' },
  'rep.maintDetail':   { en: 'MAINTENANCE DETAIL', es: 'MANTENIMIENTOS DETALLE', zh: '保养明细', de: 'WARTUNGSDETAILS', fr: 'DÉTAIL DES ENTRETIENS', ru: 'ДЕТАЛИ ОБСЛУЖИВАНИЯ' },
  'rep.inAppLink':     { en: 'Yes (in app)', es: 'Sí (ver app)', zh: '有（见应用）', de: 'Ja (in der App)', fr: 'Oui (dans l’app)', ru: 'Да (в приложении)' },
  'rep.makeModel':     { en: 'Make and model', es: 'Marca y modelo', zh: '品牌与型号', de: 'Marke und Modell', fr: 'Marque et modèle', ru: 'Марка и модель' },
  'rep.fuelCaps':      { en: 'FUEL', es: 'COMBUSTIBLE', zh: '燃料', de: 'KRAFTSTOFF', fr: 'CARBURANT', ru: 'ТОПЛИВО' },
  'rep.tasksCaps':     { en: 'TASKS', es: 'TAREAS', zh: '待办', de: 'AUFGABEN', fr: 'TÂCHES', ru: 'ЗАДАЧИ' },
  'rep.maintCaps':     { en: 'MAINTENANCE', es: 'MANTENIMIENTOS', zh: '保养', de: 'WARTUNGEN', fr: 'ENTRETIENS', ru: 'ОБСЛУЖИВАНИЕ' },
  'rep.partsCaps':     { en: 'PARTS', es: 'RECAMBIOS', zh: '配件', de: 'ERSATZTEILE', fr: 'PIÈCES', ru: 'ЗАПЧАСТИ' },
  'rep.itvFailed':     { en: 'FAILED — not roadworthy', es: 'NEGATIVA — No apta', zh: '不合格 — 不得上路', de: 'DURCHGEFALLEN — nicht verkehrssicher', fr: 'REFUSÉ — non conforme', ru: 'НЕ ПРОЙДЕН — эксплуатация запрещена' },
  'rep.repaired':      { en: 'Repaired', es: 'Reparado', zh: '已修复', de: 'Behoben', fr: 'Réparé', ru: 'Устранено' },
  'demo.exitShort':   { en: 'Exit', es: 'Salir', zh: '退出', de: 'Beenden', fr: 'Quitter', ru: 'Выйти' },
  'demo.exitConfirm': { en: 'Leave the demo and go to the sign-in screen? Your sample data stays saved for next time.', es: '¿Salir de la demo e ir a la pantalla de acceso? Los datos de ejemplo se quedan guardados para la próxima vez.', zh: '退出演示并返回登录页面？示例数据会保留，下次还在。', de: 'Demo verlassen und zur Anmeldung gehen? Die Beispieldaten bleiben für das nächste Mal gespeichert.', fr: 'Quitter la démo et aller à l’écran de connexion ? Les données d’exemple restent enregistrées pour la prochaine fois.', ru: 'Выйти из демоверсии на экран входа? Примерные данные сохранятся до следующего раза.' },
  // ══════════════════════════ GARAJE DE ESCRITORIO ══════════════════════════
  'gar.vehicles':   { en: 'Vehicles', es: 'Vehículos', zh: '车辆', de: 'Fahrzeuge', fr: 'Véhicules', ru: 'Транспорт' },
  'gar.fullCard':   { en: 'Full record', es: 'Ficha completa', zh: '完整档案', de: 'Vollständige Akte', fr: 'Fiche complète', ru: 'Полная карточка' },
  'gar.showing':    { en: 'Showing {n} of {m}', es: 'Mostrando {n} de {m}', zh: '显示 {n} / {m}', de: '{n} von {m} angezeigt', fr: '{n} sur {m} affichés', ru: 'Показано {n} из {m}' },
  'gar.viewAll':    { en: 'View all', es: 'Ver todo', zh: '查看全部', de: 'Alle ansehen', fr: 'Tout voir', ru: 'Показать всё' },
  'gar.pick':       { en: 'Pick a vehicle from the list', es: 'Elige un vehículo de la lista', zh: '从列表中选择一辆车', de: 'Wähle ein Fahrzeug aus der Liste', fr: 'Choisis un véhicule dans la liste', ru: 'Выберите машину из списка' },
  'gar.nothing':    { en: 'Nothing to show here', es: 'Nada que mostrar aquí', zh: '这里没有内容', de: 'Hier gibt es nichts', fr: 'Rien à afficher ici', ru: 'Здесь пока пусто' },

  // ══════════════════════════ GRÁFICO DE GASTO ══════════════════════════
  'chart.monthly':   { en: 'Monthly spend', es: 'Gasto mensual', zh: '每月花费', de: 'Monatliche Ausgaben', fr: 'Dépenses mensuelles', ru: 'Расходы по месяцам' },
  'chart.12m':       { en: '12 months', es: '12 meses', zh: '12 个月', de: '12 Monate', fr: '12 mois', ru: '12 месяцев' },
  'chart.thisMonth': { en: 'This month', es: 'Este mes', zh: '本月', de: 'Dieser Monat', fr: 'Ce mois-ci', ru: 'В этом месяце' },
  'chart.vsPrev':    { en: 'vs {prev} last month · average {avg}', es: 'frente a {prev} el mes pasado · media {avg}', zh: '上月 {prev} · 平均 {avg}', de: 'gegenüber {prev} im Vormonat · Schnitt {avg}', fr: 'contre {prev} le mois dernier · moyenne {avg}', ru: 'против {prev} в прошлом месяце · в среднем {avg}' },
  'chart.noSpend':   { en: 'Nothing logged in the last 12 months', es: 'Sin gastos en los últimos 12 meses', zh: '过去 12 个月没有花费记录', de: 'Keine Ausgaben in den letzten 12 Monaten', fr: 'Aucune dépense sur les 12 derniers mois', ru: 'За последние 12 месяцев расходов нет' },
  'chart.average':   { en: 'average', es: 'media', zh: '平均', de: 'Schnitt', fr: 'moyenne', ru: 'среднее' },
  'foot.rights': { en: 'All rights reserved', es: 'Todos los derechos reservados', zh: '保留所有权利', de: 'Alle Rechte vorbehalten', fr: 'Tous droits réservés', ru: 'Все права защищены' },
}
